unpackaged/main/default/objects/User/fields/AbsenceClaimsLOARole__c.field-meta.xml
<CustomField>
    <fullName>AbsenceClaimsLOARole__c</fullName>
    <label>Absence Claims LOA Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Absence Examiner 1</fullName>
            </value>
            <value>
                <fullName>Absence Examiner 2</fullName>
            </value>
            <value>
                <fullName>Sr Absence Examiner</fullName>
            </value>
            <value>
                <fullName>Absence Team Lead</fullName>
            </value>
            <value>
                <fullName>Absence Supervisor</fullName>
            </value>
            <value>
                <fullName>Absence Manager</fullName>
            </value>
            <value>
                <fullName>Claims Trainee</fullName>
            </value>
            <value>
                <fullName>Claims Auditor</fullName>
            </value>
            <value>
                <fullName>Claims Director</fullName>
            </value>
            <value>
                <fullName>Claims Sr Director</fullName>
            </value>
            <value>
                <fullName>VP Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/DisabilityClaimsLOARole__c.field-meta.xml
<CustomField>
    <fullName>DisabilityClaimsLOARole__c</fullName>
    <label>Disability Claims LOA Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Disability Claims Examiner 1</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims Examiner 2</fullName>
            </value>
            <value>
                <fullName>Group Disability Sr Claims Examiner</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims Team Lead</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims Supervisor</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims Manager</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims TDI Examiner Trainee</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims TDI Examiner 1</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims TDI Examiner 2</fullName>
            </value>
            <value>
                <fullName>Group Disability Claims TDI Examiner 3</fullName>
            </value>
            <value>
                <fullName>Claims Director</fullName>
            </value>
            <value>
                <fullName>Claims Sr Director</fullName>
            </value>
            <value>
                <fullName>VP Claims</fullName>
            </value>
            <value>
                <fullName>Claims Trainee</fullName>
            </value>
            <value>
                <fullName>Claims Auditor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/SupplementalClaimsLOARole__c.field-meta.xml
<CustomField>
    <fullName>SupplementalClaimsLOARole__c</fullName>
    <label>Supplemental Claims LOA Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplemental Claims Examiner 1</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Examiner 2</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Examiner 3</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Examiner 4</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Team Lead</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Supervisor</fullName>
            </value>
            <value>
                <fullName>Supplemental Claims Manager</fullName>
            </value>
            <value>
                <fullName>Claims Director</fullName>
            </value>
            <value>
                <fullName>Claims Sr Director</fullName>
            </value>
            <value>
                <fullName>VP Claims</fullName>
            </value>
            <value>
                <fullName>Claims Trainee</fullName>
            </value>
            <value>
                <fullName>Claims Auditor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestUserBuilder.cls
@IsTest
public class TestUserBuilder extends TestSObjectBuilder {
  // keeps count of Instances to allow differentiating objects built;
  // e.g. 'Test Account 1', 'Test Account 2'
  // specifically, increments when build() is called.
  static Integer iteration = 0;

  public TestUserBuilder() {
    setSObjectAndDefaultRecordType('User', null);

    this.values.put('builderId', iteration + 1);
    addDefaultFieldsToValuesMap();
  }

  private TestUserBuilder(TestUserBuilder oldBuilder) {
    this.values = oldBuilder.values;
    this.SOBJECT_TYPE = oldBuilder.SOBJECT_TYPE;
    this.DEFAULT_SOBJECT_RECORD_TYPE = oldBuilder.DEFAULT_SOBJECT_RECORD_TYPE;
  }

  // candidate for abstract class (??)... or candidate for required method?
  protected override TestSObjectBuilder cloneBuilder() {
    TestUserBuilder newBuilder = new TestUserBuilder(this);

    Integer newBuilderId = (Integer) newBuilder.values.get('builderId');
    newBuilder.values.put('builderId', newBuilderId + 1);
    return newBuilder;
  }

  // default values that apply to all instances across all tests
  protected override void addDefaultFieldsToValuesMap() {
    this.copyRunningUser();
  }

  // candidate for abstract class -- using Type.forName() ??
  protected override void iterate() {
    TestUserBuilder.iteration += 1;
  }

  // setters
  public TestUserBuilder copyRunningUser() {
    User u = [
      SELECT
        LastName,
        FirstName,
        Alias,
        Email,
        Username,
        ProfileId,
        TimeZoneSidKey,
        LanguageLocaleKey,
        EmailEncodingKey,
        LocaleSidKey
      FROM User
      WHERE Id = :UserInfo.getUserId()
      LIMIT 1
    ];
    values.put('LastName', u.LastName);
    values.put('FirstName', u.FirstName);
    values.put('Alias', 'tus' + (Math.roundToLong(Math.random() * 100)));
    values.put('Email', 'testuser@example.com');
    values.put(
      'Username',
      u.Username + String.valueOf(Math.roundToLong(Math.random() * 100000))
    );
    values.put('ProfileId', u.ProfileId);
    values.put('TimeZoneSidKey', u.TimeZoneSidKey);
    values.put('LanguageLocaleKey', u.LanguageLocaleKey);
    values.put('EmailEncodingKey', u.EmailEncodingKey);
    values.put('LocaleSidKey', u.LocaleSidKey);
    values.put('AbsenceClaimsLOARole__c', 'Claims Director');
    values.put('DisabilityClaimsLOARole__c', 'Claims Director');
    values.put('SupplementalClaimsLOARole__c', 'Claims Director');
    return (TestUserBuilder) cloneBuilder();
  }

  public TestUserBuilder withProfileName(String profileName) {
    Id profileId = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1]
    .Id;
    values.put('ProfileId', profileId);
    return (TestUserBuilder) cloneBuilder();
  }

  public TestUserBuilder withLastName(String lastName) {
    values.put('LastName', lastName);
    return (TestUserBuilder) cloneBuilder();
  }

  public TestUserBuilder withAbsenceLOARole(String role) {
    values.put('AbsenceClaimsLOARole__c', role);
    return (TestUserBuilder) cloneBuilder();
  }

  public TestUserBuilder withDisabilityLOARole(String role) {
    values.put('DisabilityClaimsLOARole__c', role);
    return (TestUserBuilder) cloneBuilder();
  }

  public TestUserBuilder withSupplementalLOARole(String role) {
    values.put('SupplementalClaimsLOARole__c', role);
    return (TestUserBuilder) cloneBuilder();
  }
}