unpackaged/main/default/objects/AdditionalIncome__c/AdditionalIncome__c.object-meta.xml
<CustomObject>
    <label>Additional Income</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/IncomeType__c.field-meta.xml
<CustomField>
    <fullName>IncomeType__c</fullName>
    <label>Income Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>PFML Income</fullName>
            </value>
            <value>
                <fullName>STD Income</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/PaymentSpecification__c.field-meta.xml
<CustomField>
    <fullName>PaymentSpecification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Specification</label>
    <referenceTo>cve__PaymentSpecification__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>AdditionalIncomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>BiWeekly</fullName>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>SemiMonthly</fullName>
                <label>Semi-Monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>HalfYearly</fullName>
                <label>Half-Yearly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/PFMLClaim__c.field-meta.xml
<CustomField>
    <fullName>PFMLClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PFML Claim</label>
    <referenceTo>cvab__Claim__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>AdditionalIncomes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/STDClaim__c.field-meta.xml
<CustomField>
    <fullName>STDClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>STD Claim</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>Additional_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/AdditionalIncomeOffset__e.object-meta.xml
<CustomObject>
    <label>Additional Income Offset</label>
    <pluralLabel>Additional Income Offsets</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/fields/OffsetIncomeData__c.field-meta.xml
<CustomField>
    <fullName>OffsetIncomeData__c</fullName>
    <label>Offset Income Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/AdditionalIncomeTriggerTest.cls
@isTest
public class AdditionalIncomeTriggerTest {
  @TestSetup
  public static void testSetup() {
    cvab__Claim__c absence = new cvab__Claim__c();
    insert absence;
    cve__Claim__c disability = new cve__Claim__c(
      cvint__AbsenceClaim__c = absence.id
    );
    insert disability;
    cve__PaymentSpecification__c ps = new cve__PaymentSpecification__c(
      cve__Claim__c = disability.id,
      cvint__AbsenceClaim__c = null
    );
    insert ps;
  }

  @isTest
  public static void insert_additional_income_for_nonintegrated_disability() {
    cve__PaymentSpecification__c ps = queryPaymentSpec();
    cve__Claim__c disability = [
      SELECT Id, cvint__AbsenceClaim__c
      FROM cve__Claim__c
    ];

    disability.cvint__AbsenceClaim__c = null;
    update disability;
    cvab__Claim__c absence = [SELECT id FROM cvab__Claim__c];

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 2000.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = ps.id,
      Period__c = 'Yearly',
      StartDate__c = Date.newInstance(2024, 1, 1),
      PFMLClaim__c = null,
      STDClaim__c = null
    );
    insert income;
    TriggerHandler.clearAllBypasses();

    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeTriggerHandler testHandler = new AdditionalIncomeTriggerHandler(
      AdditionalIncomeTriggerHelper.getHelperInstance(),
      null,
      new List<AdditionalIncome__c>{ income },
      eventPublisherDouble
    );
    testHandler.afterInsert();

    Test.stopTest();

    OffsetEvent result = new OffsetEvent(
      queryPaymentSpec(),
      disability,
      null,
      getRelatedAdditionalIncomes(ps.id)
    );
    AdditionalIncomeOffset__e expectedOutcome = new AdditionalIncomeOffset__e(
      OffsetIncomeData__c = JSON.serialize(result)
    );
    List<AdditionalIncomeOffset__e> actualOutcome = (List<AdditionalIncomeOffset__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');

    Assert.areEqual(
      new List<AdditionalIncomeOffset__e>{ expectedOutcome },
      actualOutcome,
      'Published AdditionalIncomeOffset__e does not match expected AdditionalIncomeOffset__e'
    );
  }

  @isTest
  public static void insert_additional_income_for_integrated_disability() {
    cve__PaymentSpecification__c ps = queryPaymentSpec();
    cve__Claim__c disability = [
      SELECT Id, cvint__AbsenceClaim__c
      FROM cve__Claim__c
    ];

    cvab__Claim__c absence = [SELECT id FROM cvab__Claim__c];

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 2000.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = ps.id,
      Period__c = 'Yearly',
      StartDate__c = Date.newInstance(2024, 1, 1),
      PFMLClaim__c = null,
      STDClaim__c = null
    );
    insert income;
    TriggerHandler.clearAllBypasses();

    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeTriggerHandler testHandler = new AdditionalIncomeTriggerHandler(
      AdditionalIncomeTriggerHelper.getHelperInstance(),
      null,
      new List<AdditionalIncome__c>{ income },
      eventPublisherDouble
    );
    testHandler.afterInsert();

    Test.stopTest();

    OffsetEvent result = new OffsetEvent(
      queryPaymentSpec(),
      disability,
      absence,
      getRelatedAdditionalIncomes(ps.id)
    );
    AdditionalIncomeOffset__e expectedOutcome = new AdditionalIncomeOffset__e(
      OffsetIncomeData__c = JSON.serialize(result)
    );
    List<AdditionalIncomeOffset__e> actualOutcome = (List<AdditionalIncomeOffset__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');

    Assert.areEqual(
      new List<AdditionalIncomeOffset__e>{ expectedOutcome },
      actualOutcome,
      'Published AdditionalIncomeOffset__e does not match expected AdditionalIncomeOffset__e'
    );
  }

  @isTest
  public static void insert_additional_income_for_nonintegrated_absence() {
    cve__PaymentSpecification__c ps = queryPaymentSpec();

    cvab__Claim__c absence = [SELECT id FROM cvab__Claim__c];

    ps.cvint__AbsenceClaim__c = absence.Id;
    ps.cve__Claim__c = null;
    update ps;

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 2000.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = ps.id,
      Period__c = 'Yearly',
      StartDate__c = Date.newInstance(2024, 1, 1),
      PFMLClaim__c = null,
      STDClaim__c = null
    );
    insert income;
    TriggerHandler.clearAllBypasses();

    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeTriggerHandler testHandler = new AdditionalIncomeTriggerHandler(
      AdditionalIncomeTriggerHelper.getHelperInstance(),
      null,
      new List<AdditionalIncome__c>{ income },
      eventPublisherDouble
    );
    testHandler.afterInsert();

    Test.stopTest();

    OffsetEvent result = new OffsetEvent(
      queryPaymentSpec(),
      null,
      absence,
      getRelatedAdditionalIncomes(ps.id)
    );
    AdditionalIncomeOffset__e expectedOutcome = new AdditionalIncomeOffset__e(
      OffsetIncomeData__c = JSON.serialize(result)
    );
    List<AdditionalIncomeOffset__e> actualOutcome = (List<AdditionalIncomeOffset__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');

    Assert.areEqual(
      new List<AdditionalIncomeOffset__e>{ expectedOutcome },
      actualOutcome,
      'Published AdditionalIncomeOffset__e does not match expected AdditionalIncomeOffset__e'
    );
  }

  @isTest
  public static void updateAdditionalIncomeTest() {
    cve__PaymentSpecification__c ps = queryPaymentSpec();
    cve__Claim__c disability = [
      SELECT Id, cvint__AbsenceClaim__c
      FROM cve__Claim__c
    ];
    cvab__Claim__c absence = [SELECT id FROM cvab__Claim__c];

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 2000.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = ps.id,
      Period__c = 'Yearly',
      StartDate__c = Date.newInstance(2024, 1, 1),
      PFMLClaim__c = null,
      STDClaim__c = null
    );
    insert income;
    TriggerHandler.clearAllBypasses();

    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeTriggerHandler testHandler = new AdditionalIncomeTriggerHandler(
      AdditionalIncomeTriggerHelper.getHelperInstance(),
      null,
      new List<AdditionalIncome__c>{ income },
      eventPublisherDouble
    );
    testHandler.afterUpdate();

    Test.stopTest();

    OffsetEvent result = new OffsetEvent(
      queryPaymentSpec(),
      disability,
      absence,
      getRelatedAdditionalIncomes(ps.id)
    );
    AdditionalIncomeOffset__e expectedOutcome = new AdditionalIncomeOffset__e(
      OffsetIncomeData__c = JSON.serialize(result)
    );
    List<AdditionalIncomeOffset__e> actualOutcome = (List<AdditionalIncomeOffset__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');

    Assert.areEqual(
      new List<AdditionalIncomeOffset__e>{ expectedOutcome },
      actualOutcome,
      'Published AdditionalIncomeOffset__e does not match expected AdditionalIncomeOffset__e'
    );
  }

  // WICKED FRAGILE - TESTS DEPEND ON SAME ORDER OF QUERIED FIELDS AS HANDLER IN ORDER TO ASSERT TRUE
  public static List<AdditionalIncome__c> getRelatedAdditionalIncomes(
    Id paymentSpecId
  ) {
    return [
      SELECT
        PaymentSpecification__c,
        Id,
        Name,
        Amount__c,
        EndDate__c,
        IncomeType__c,
        Period__c,
        StartDate__c,
        PFMLClaim__c,
        STDClaim__c
      FROM AdditionalIncome__c
      WHERE PaymentSpecification__c = :paymentSpecId
    ];
  }

  // WICKED FRAGILE - TESTS DEPEND ON SAME ORDER OF QUERIED FIELDS AS HANDLER IN ORDER TO ASSERT TRUE
  static cve__PaymentSpecification__c queryPaymentSpec() {
    return [
      SELECT
        Id,
        cvint__AbsenceClaim__c,
        cve__Claim__c,
        cve__Claim__r.cvint__AbsenceClaim__c,
        (
          SELECT
            Id,
            Name,
            Amount__c,
            EndDate__c,
            IncomeType__c,
            PaymentSpecification__c,
            Period__c,
            StartDate__c,
            PFMLClaim__c,
            STDClaim__c
          FROM AdditionalIncomes__r
        )
      FROM cve__PaymentSpecification__c
      LIMIT 1
    ];
  }
}