unpackaged/main/default/objects/AdditionalIncome__c/AdditionalIncome__c.object-meta.xml
<CustomObject>
    <label>Additional Income</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/IncomeType__c.field-meta.xml
<CustomField>
    <fullName>IncomeType__c</fullName>
    <label>Income Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>PFML Income</fullName>
            </value>
            <value>
                <fullName>STD Income</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/PaymentSpecification__c.field-meta.xml
<CustomField>
    <fullName>PaymentSpecification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Specification</label>
    <referenceTo>cve__PaymentSpecification__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>AdditionalIncomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>BiWeekly</fullName>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>SemiMonthly</fullName>
                <label>Semi-Monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>HalfYearly</fullName>
                <label>Half-Yearly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/PFMLClaim__c.field-meta.xml
<CustomField>
    <fullName>PFMLClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PFML Claim</label>
    <referenceTo>cvab__Claim__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>AdditionalIncomes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/STDClaim__c.field-meta.xml
<CustomField>
    <fullName>STDClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>STD Claim</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>Additional_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/AdditionalIncomeOffset__e.object-meta.xml
<CustomObject>
    <label>Additional Income Offset</label>
    <pluralLabel>Additional Income Offsets</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/fields/OffsetIncomeData__c.field-meta.xml
<CustomField>
    <fullName>OffsetIncomeData__c</fullName>
    <label>Offset Income Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/AdditionalIncomeTriggerHelper.cls
public class AdditionalIncomeTriggerHelper {
  private static AdditionalIncomeTriggerHelper instance = null;

  public static AdditionalIncomeTriggerHelper getHelperInstance() {
    if (instance == null) {
      instance = new AdditionalIncomeTriggerHelper();
    }

    return instance;
  }

  public List<AdditionalIncomeOffset__e> generatePlatformEvents(
    List<AdditionalIncome__c> incomeList
  ) {
    Set<Id> paymentSpecIds = new Set<id>();
    for (AdditionalIncome__c obj : incomeList) {
      paymentSpecIds.add(obj.PaymentSpecification__c);
    }
    Map<Id, cve__PaymentSpecification__c> paymentSpecificationMap = getAllPaymentSpecification(
      paymentSpecIds
    );

    List<String> stringList = generateJsonFromObjects(paymentSpecificationMap);

    List<AdditionalIncomeOffset__e> events = new List<AdditionalIncomeOffset__e>();
    for (String json : stringList) {
      AdditionalIncomeOffset__e event = new AdditionalIncomeOffset__e();
      event.OffsetIncomeData__c = json;
      events.add(event);
    }

    return events;
  }

  public Map<id, cve__PaymentSpecification__c> getAllPaymentSpecification(
    Set<id> paymentSpecIds
  ) {
    Map<id, cve__PaymentSpecification__c> result = new Map<id, cve__PaymentSpecification__c>(
      [
        SELECT
          Id,
          cvint__AbsenceClaim__c,
          cve__Claim__c,
          cve__Claim__r.cvint__AbsenceClaim__c,
          (
            SELECT
              Id,
              Name,
              Amount__c,
              EndDate__c,
              IncomeType__c,
              PaymentSpecification__c,
              Period__c,
              StartDate__c,
              PFMLClaim__c,
              STDClaim__c
            FROM AdditionalIncomes__r
          )
        FROM cve__PaymentSpecification__c
        WHERE ID IN :paymentSpecIds
      ]
    );
    return result;
  }

  public List<String> generateJsonFromObjects(
    Map<id, cve__PaymentSpecification__c> paymentSpecMap
  ) {
    List<String> result = new List<String>();

    for (Id psId : paymentSpecMap.keySet()) {
      cve__PaymentSpecification__c ps = null;
      cve__Claim__c cveClaim = null;
      cvab__Claim__c cvabClaim = null;
      List<AdditionalIncome__c> incomeList = null;

      ps = paymentSpecMap.get(psId);
      incomeList = ps.AdditionalIncomes__r;
      cveClaim = buildCveClaim(ps);
      cvabClaim = buildCvabClaim(ps);
      result.add(
        JSON.serialize(new OffsetEvent(ps, cveClaim, cvabClaim, incomeList))
      );
    }
    system.debug(result);
    return result;
  }

  private cve__Claim__c buildCveClaim(
    cve__PaymentSpecification__c paymentSpec
  ) {
    cve__Claim__c cveClaim;

    if (paymentSpec.cve__Claim__c != null) {
      cveClaim = new cve__Claim__c(
        Id = paymentSpec.cve__Claim__c,
        cvint__AbsenceClaim__c = paymentSpec.cve__Claim__r
          ?.cvint__AbsenceClaim__c
      );
    }

    return cveClaim;
  }
  private cvab__Claim__c buildCvabClaim(
    cve__PaymentSpecification__c paymentSpec
  ) {
    cvab__Claim__c cvabClaim;

    if (paymentSpec.cvint__AbsenceClaim__c != null) {
      cvabClaim = new cvab__Claim__c(Id = paymentSpec.cvint__AbsenceClaim__c);
    } else if (paymentSpec.cve__Claim__r.cvint__AbsenceClaim__c != null) {
      cvabClaim = new cvab__Claim__c(
        Id = paymentSpec.cve__Claim__r.cvint__AbsenceClaim__c
      );
    }

    return cvabClaim;
  }
}