unpackaged/main/default/objects/AdditionalIncome__c/AdditionalIncome__c.object-meta.xml
<CustomObject>
    <label>Additional Income</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/IncomeType__c.field-meta.xml
<CustomField>
    <fullName>IncomeType__c</fullName>
    <label>Income Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>PFML Income</fullName>
            </value>
            <value>
                <fullName>STD Income</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/PaymentSpecification__c.field-meta.xml
<CustomField>
    <fullName>PaymentSpecification__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Specification</label>
    <referenceTo>cve__PaymentSpecification__c</referenceTo>
    <relationshipLabel>Additional Incomes</relationshipLabel>
    <relationshipName>AdditionalIncomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>BiWeekly</fullName>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>SemiMonthly</fullName>
                <label>Semi-Monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>HalfYearly</fullName>
                <label>Half-Yearly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AdditionalIncome__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/AdditionalIncomeOffset__e.object-meta.xml
<CustomObject>
    <label>Additional Income Offset</label>
    <pluralLabel>Additional Income Offsets</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AdditionalIncomeOffset__e/fields/OffsetIncomeData__c.field-meta.xml
<CustomField>
    <fullName>OffsetIncomeData__c</fullName>
    <label>Offset Income Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/RecalculatePayments__e/RecalculatePayments__e.object-meta.xml
<CustomObject>
    <label>Recalculate Payments</label>
    <pluralLabel>Recalculate Payments</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/RecalculatePayments__e/fields/PaymentSpecificationId__c.field-meta.xml
<CustomField>
    <fullName>PaymentSpecificationId__c</fullName>
    <label>Payment Specification Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AdditionalIncomeOffsetTriggerTest.cls
@isTest
public class AdditionalIncomeOffsetTriggerTest {
  @TestSetup
  public static void testSetup() {
    cve__Claim__c cveClaim = new cve__Claim__c();
    insert cveClaim;

    cvab__Claim__c cvabClaim = new cvab__Claim__c();
    insert cvabClaim;
    cve__PaymentSpecification__c ps1 = new cve__PaymentSpecification__c(
      cve__Claim__c = cveClaim.id,
      cvint__AbsenceClaim__c = null
    );
    insert ps1;
    cve__PaymentSpecification__c ps2 = new cve__PaymentSpecification__c(
      cve__Claim__c = null,
      cvint__AbsenceClaim__c = cvabClaim.id
    );
    insert ps2;
  }

  @isTest
  public static void triggerTest() {
    cve__Claim__c c1 = getCveClaim();
    cve__PaymentSpecification__c p1 = getCvePaymentSpec(c1.id);

    Test.startTest();
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = p1.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income;
    Test.stopTest();

    Assert.areEqual(
      1,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :p1.id
        ]
        .size()
    );
  }

  @isTest
  public static void additionalIncome_on_cveClaim_creates_adjustments() {
    cve__Claim__c c1 = getCveClaim();
    cve__PaymentSpecification__c p1 = getCvePaymentSpec(c1.id);
    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = p1.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income;
    TriggerHandler.clearAllBypasses();
    OffsetEvent eventPayload = new OffsetEvent(
      p1,
      c1,
      null,
      new List<AdditionalIncome__c>{ income }
    );
    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeOffsetTriggerHandler handler = new AdditionalIncomeOffsetTriggerHandler(
      AdditionalIncomeOffsetTriggerHelper.getInstance(),
      new List<AdditionalIncomeOffset__e>{
        new AdditionalIncomeOffset__e(
          OffsetIncomeData__c = JSON.serialize(eventPayload)
        )
      },
      eventPublisherDouble
    );
    handler.afterInsert();

    Test.stopTest();

    List<RecalculatePayments__e> actualOutcome = (List<RecalculatePayments__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');

    Assert.areEqual(
      new List<RecalculatePayments__e>{
        new RecalculatePayments__e(PaymentSpecificationId__c = p1.id)
      },
      actualOutcome
    );
    Assert.areEqual(
      1,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :p1.id
        ]
        .size()
    );
  }

  @isTest
  public static void additionalIncome_on_cvabClaim_creates_adjustments() {
    cvab__Claim__c c1 = getCvabClaim();
    cve__PaymentSpecification__c p1 = getCvabPaymentSpec(c1.id);
    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = p1.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income;
    TriggerHandler.clearAllBypasses();
    OffsetEvent eventPayload = new OffsetEvent(
      p1,
      null,
      c1,
      new List<AdditionalIncome__c>{ income }
    );
    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeOffsetTriggerHandler handler = new AdditionalIncomeOffsetTriggerHandler(
      AdditionalIncomeOffsetTriggerHelper.getInstance(),
      new List<AdditionalIncomeOffset__e>{
        new AdditionalIncomeOffset__e(
          OffsetIncomeData__c = JSON.serialize(eventPayload)
        )
      },
      eventPublisherDouble
    );
    handler.afterInsert();

    Test.stopTest();

    List<RecalculatePayments__e> actualOutcome = (List<RecalculatePayments__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');
    Assert.areEqual(
      new List<RecalculatePayments__e>{
        new RecalculatePayments__e(PaymentSpecificationId__c = p1.id)
      },
      actualOutcome
    );
    Assert.areEqual(
      1,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :p1.id
        ]
        .size()
    );
  }

  @isTest
  public static void pfmlAdditionalIncome_on_IntegratedClaim_creates_adjustments() {
    cve__Claim__c cveClaim = getCveClaim();
    cve__PaymentSpecification__c cvePaymentSpec = getCvePaymentSpec(
      cveClaim.id
    );
    cvab__Claim__c cvabClaim = getCvabClaim();
    cve__PaymentSpecification__c cvabPaymentSpec = getCvabPaymentSpec(
      cvabClaim.id
    );
    cveClaim.cvint__AbsenceClaim__c = cvabClaim.id;
    cvabClaim.cvint__DisabilityClaim__c = cveClaim.id;

    update cveClaim;
    update cvabClaim;

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PFML Income',
      PaymentSpecification__c = cvePaymentSpec.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income;
    TriggerHandler.clearAllBypasses();
    OffsetEvent eventPayload = new OffsetEvent(
      cvePaymentSpec,
      cveClaim,
      cvabClaim,
      new List<AdditionalIncome__c>{ income }
    );
    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeOffsetTriggerHandler handler = new AdditionalIncomeOffsetTriggerHandler(
      AdditionalIncomeOffsetTriggerHelper.getInstance(),
      new List<AdditionalIncomeOffset__e>{
        new AdditionalIncomeOffset__e(
          OffsetIncomeData__c = JSON.serialize(eventPayload)
        )
      },
      eventPublisherDouble
    );
    handler.afterInsert();

    Test.stopTest();

    List<RecalculatePayments__e> actualOutcome = (List<RecalculatePayments__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');
    Assert.areEqual(
      new List<RecalculatePayments__e>{
        new RecalculatePayments__e(
          PaymentSpecificationId__c = cvePaymentSpec.id
        )
      },
      actualOutcome
    );
    Assert.areEqual(
      1,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :cvePaymentSpec.id
        ]
        .size()
    );
  }

  @isTest
  public static void stdAdditionalIncome_on_IntegratedClaim_creates_adjustments() {
    cve__Claim__c cveClaim = getCveClaim();
    cve__PaymentSpecification__c cvePaymentSpec = getCvePaymentSpec(
      cveClaim.id
    );
    cvab__Claim__c cvabClaim = getCvabClaim();
    cve__PaymentSpecification__c cvabPaymentSpec = getCvabPaymentSpec(
      cvabClaim.id
    );
    cveClaim.cvint__AbsenceClaim__c = cvabClaim.id;
    cvabClaim.cvint__DisabilityClaim__c = cveClaim.id;

    update cveClaim;
    update cvabClaim;

    TriggerHandler.bypass('AdditionalIncomeTriggerHandler');
    AdditionalIncome__c income1 = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'STD Income',
      PaymentSpecification__c = cvePaymentSpec.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income1;
    AdditionalIncome__c income2 = new AdditionalIncome__c(
      Name = 'test',
      Amount__c = 200.00,
      EndDate__c = Date.newInstance(2024, 1, 1),
      IncomeType__c = 'PTO',
      PaymentSpecification__c = cvePaymentSpec.id,
      Period__c = 'Weekly',
      StartDate__c = Date.newInstance(2024, 1, 1)
    );
    insert income2;
    TriggerHandler.clearAllBypasses();
    OffsetEvent eventPayload = new OffsetEvent(
      cvePaymentSpec,
      cveClaim,
      cvabClaim,
      new List<AdditionalIncome__c>{ income1, income2 }
    );
    Amoss_Instance mockEventPublisher = new Amoss_Instance(
      EventPublisher.class
    );
    mockEventPublisher.byDefaultMethodsReturn(new List<Database.SaveResult>());
    EventPublisher eventPublisherDouble = (EventPublisher) mockEventPublisher.getDouble();

    Test.startTest();

    AdditionalIncomeOffsetTriggerHandler handler = new AdditionalIncomeOffsetTriggerHandler(
      AdditionalIncomeOffsetTriggerHelper.getInstance(),
      new List<AdditionalIncomeOffset__e>{
        new AdditionalIncomeOffset__e(
          OffsetIncomeData__c = JSON.serialize(eventPayload)
        )
      },
      eventPublisherDouble
    );
    handler.afterInsert();

    Test.stopTest();

    List<RecalculatePayments__e> actualOutcome = (List<RecalculatePayments__e>) mockEventPublisher.call(
        0
      )
      .of('publish')
      .parameter('events');
    Assert.areEqual(
      new List<RecalculatePayments__e>{
        new RecalculatePayments__e(
          PaymentSpecificationId__c = cvabPaymentSpec.id
        ),
        new RecalculatePayments__e(
          PaymentSpecificationId__c = cvePaymentSpec.id
        )
      },
      actualOutcome
    );
    Assert.areEqual(
      2,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :cvabPaymentSpec.id
        ]
        .size()
    );
    Assert.areEqual(
      1,
      [
          SELECT id
          FROM cve__Adjustment__c
          WHERE cve__PaymentSpecification__c = :cvePaymentSpec.id
        ]
        .size()
    );
  }

  public static cve__Claim__c getCveClaim() {
    return [SELECT id FROM cve__Claim__c];
  }

  public static cvab__Claim__c getCvabClaim() {
    return [SELECT id FROM cvab__Claim__c];
  }

  public static cve__PaymentSpecification__c getCvePaymentSpec(Id claimId) {
    return [
      SELECT id
      FROM cve__PaymentSpecification__c
      WHERE cve__Claim__c = :claimId
    ];
  }

  public static cve__PaymentSpecification__c getCvabPaymentSpec(Id claimId) {
    return [
      SELECT id
      FROM cve__PaymentSpecification__c
      WHERE cvint__AbsenceClaim__c = :claimId
    ];
  }
}