unpackaged/main/default/objects/Account/fields/Account_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Name__c</fullName>
    <description>Used for conversion of Prospect to Master Group, so that field values are populated in the chatter post instead of IDs.</description>
    <formula>Owner.FirstName +&#39; &#39;+Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Blue_Rep_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Blue_Rep_Name_Text__c</fullName>
    <description>Used for conversion of Prospect to Master Group, so that field values are populated in the chatter post instead of IDs.</description>
    <formula>Blue_Rep_Name__r.FirstName +&#39; &#39;+ Blue_Rep_Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Blue Rep Name Text</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Blue_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Blue_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Name__c</fullName>
    <description>Used for conversion of Prospect to Master Group, so that field values are populated in the chatter post instead of IDs.</description>
    <formula>County__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Group_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Key_Client__c.field-meta.xml
<CustomField>
    <fullName>Key_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Client</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <inlineHelpText>FL uses Small, Mid-Market and Large.
AR uses Small and Large.
HI uses the others.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this field is populated on a Partner record, the Opportunities, Contacts, and Activities are moved over to the Master Group, chatter post created on master group, and Prospect record is deleted.</description>
    <inlineHelpText>Enter the name of the master group to merge this Prospect with the specified Master Group.</inlineHelpText>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Master_Group</value>
        </filterItems>
        <filterItems>
            <field>Account.Partner__c</field>
            <operation>equals</operation>
            <valueField>$Source.Partner__c</valueField>
        </filterItems>
        <infoMessage>You can only associate a Prospect with a Master Group</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Master Group)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Agency_Name__c</fullName>
    <description>This field will be used on Opportunity Quick Close grid. It will be labelled as Broker Agency.</description>
    <formula>Sales_Primary_Agency__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Agency Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Accounts</description>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>New Prospect Accounts</description>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/globalValueSets/Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>Large</fullName>
    </customValue>
    <customValue>
        <fullName>CRG</fullName>
    </customValue>
    <customValue>
        <fullName>ACA</fullName>
    </customValue>
    <customValue>
        <fullName>MRG</fullName>
    </customValue>
    <customValue>
        <fullName>ASO/AFM</fullName>
    </customValue>
    <customValue>
        <fullName>RRG</fullName>
    </customValue>
    <customValue>
        <fullName>State</fullName>
    </customValue>
    <customValue>
        <fullName>FED</fullName>
    </customValue>
    <customValue>
        <fullName>Mid Market</fullName>
        <isActive>false</isActive>
        <label>Mid Market</label>
    </customValue>
    <customValue>
        <fullName>Large Market</fullName>
        <isActive>false</isActive>
        <label>Large Market</label>
    </customValue>
    <customValue>
        <fullName>Small Market</fullName>
        <isActive>false</isActive>
        <label>Small Market</label>
    </customValue>
    <description>Contains the picklist values for segment.</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ProspectConvertMG.cls
/*
Name        : ProspectConvertMG
Author      : Zaid Ali
Date        : 3/28/2017
Purpose     : To convert Prospect account into Master Group with reparenting
*/



Public without sharing class ProspectConvertMG {

    public static void ConverIntoMG(List <Account> lstAcc){
    
        system.debug('In Class for Conversion '+lstAcc);
        
        set <Id> setofAccountIds = new Set<Id>();
        List <Account> lstAccounts = new list <Account>();
        List <Opportunity> lstOpp = new List <Opportunity>();
        List <Opportunity> lstOppToUpdate = new List <Opportunity>();
        List <Contact> lstContacts = new List <Contact>();
        List <Contact> lstContactsToAdd = new List <Contact>();
        List <Task> lstEvents = new List <Task>();
        List <Task> lstEventsToAdd = new List <Task>();
        List <Id> lstAccIdToDelete = new List <Id>();
        
        Map <Id, Id> MapOfPIdAndMGId = new Map <Id, Id>(); 
        
        //Get all the Account and put them into respective lists
        For (Account AC : lstAcc)
        {
            setofAccountIds.add(AC.Id);
            MapOfPIdAndMGId.put(AC.Id,AC.Master_Group__c);
            lstAccounts.add(AC);
            lstAccIdToDelete.add(AC.Id);
        }
        
        // reparenting Opportunity Starts here
        
        // Query all the opportunities related to the account
        lstOpp = [Select Id, AccountId From Opportunity where AccountId IN : lstAcc];
        
        for(Opportunity Opp : lstOpp)
        {
            if (MapOfPIdAndMGId.containskey(Opp.AccountId))
            {
                Opp.AccountId = MapOfPIdAndMGId.get(Opp.AccountId); // reparent Opportunity
                lstOppToUpdate.add(Opp);
            }
        }
         update lstOppToUpdate;

        // reparenting Opportunity Ends here
        
        // reparenting Contacts Starts here
        lstContacts = [Select Id, AccountId from Contact where AccountId IN : lstAcc];
        for (Contact Con : lstContacts)
        {
            if (MapOfPIdAndMGId.containskey(Con.AccountId))
            {
                Con.AccountId = MapOfPIdAndMGId.get(Con.AccountId); //reparenting account here
                lstContactsToAdd.add(Con);
            }
        }
         update lstContactsToAdd;
        
        // reparenting Contacts ends here
        
        // creating chatter post data
        
        Id CurrentUserId = userinfo.getuserid();
        String CurrentUserFirstName = userinfo.getFirstName();
        if(CurrentUserFirstName == null)
        CurrentUserFirstName = '';
        
        String CurrentUserLastName = userinfo.getLastName(); 
        if(CurrentUserLastName == null)
        CurrentUserLastName = '';
        
        String CurrentUserName = CurrentUserFirstName +' '+ CurrentUserLastName;
        
        list <FeedItem> lstFeedItem = new List <FeedItem>();
        
        // creating chatter post for Master Group Accounts
        
        for (Account Acc : lstAccounts)
        {
            //Adding a Text post
            FeedItem post = new FeedItem();
            post.ParentId = MapOfPIdAndMGId.get(Acc.Id); //Accountid for mg account..
            post.Body = 'Prospect Account Merged :  '+Acc.name+'\r\n'+
            'Account Id : '+Acc.Id+'\r\n'+
            'Street : '+Acc.BillingStreet+'\r\n'+
            'BillingCity : '+Acc.BillingCity+'\r\n'+
            'Billing State : '+Acc.BillingState+'\r\n'+
            'Billing Country : '+Acc.BillingCountry+'\r\n'+
            'Billing Postal Code : '+Acc.BillingPostalCode+'\r\n'+
            'County : '+Acc.County_Name__c+'\r\n'+
            'Billing Postal Code : '+Acc.BillingPostalCode+'\r\n'+
            'Fax : '+Acc.Fax+'\r\n'+
            'Website : '+Acc.website+'\r\n'+
            'Key Client : '+Acc.Key_Client__c+'\r\n'+
            'Primary Agency : '+Acc.Primary_Agency_Name__c+'\r\n'+
            'SIC Code : '+Acc.Sic+'\r\n'+
            'Group Anniversary Date : '+Acc.Group_Anniversary_Date__c+'\r\n'+
            'Market Segment : '+Acc.Market_Segment__c+'\r\n'+
            'Sector : '+Acc.Sector__c+'\r\n'+
            'Account Owner : '+Acc.Account_Owner_Name__c+'\r\n'+
            'Blue Rep Name : '+Acc.Blue_Rep_Name_Text__c+'\r\n'+
            'Blue Rep Territory Code : '+Acc.Blue_Territory_Code__c+'\r\n'+
            'Master Group on Prospect Updated by : '+CurrentUserName+'\r\n'+
            'Master Group on Prospect Updated by Id : '+CurrentUserId+'\r\n';
            
            
            lstFeedItem.add(post);
           
        }
        insert lstFeedItem;
        
        ProspectConvertMG.processRecords(lstAccIdToDelete);
        
    }
    

    // This method is a future call which will delete the prospect account after reparenting
    @future
    public static void processRecords(List<ID> recordIds)
    {   
         // Get those records based on the IDs
         List<Account> accts = [SELECT Id, Name FROM Account WHERE Id IN :recordIds];
         // Delete records
         delete accts;
    }


}