unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(TEXT(Group_Termination_Date__c) =  null,True,IF(Group_Termination_Date__c &gt;  TODAY(), True,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Blue_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Blue_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will hold the relevant county for account.</description>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Key_Client__c.field-meta.xml
<CustomField>
    <fullName>Key_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Client</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LSV_Business__c.field-meta.xml
<CustomField>
    <fullName>LSV_Business__c</fullName>
    <inlineHelpText>&#39;Medical Only&#39; - Master Group has only medical asset
&#39;Medical and Ancillary&#39; - Master Group has medical asset and at least one ancillary asset
&#39;Ancillary Only&#39; - Master Group has no medical asset and at least one ancillary asset</inlineHelpText>
    <label>LSV Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LSV Customer</fullName>
            </value>
            <value>
                <fullName>Medical Only</fullName>
            </value>
            <value>
                <fullName>Ancillary Only</fullName>
            </value>
            <value>
                <fullName>Medical and Ancillary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LSV_Group_Size__c.field-meta.xml
<CustomField>
    <fullName>LSV_Group_Size__c</fullName>
    <label>LSV Group Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <inlineHelpText>FL uses Small, Mid-Market and Large.
AR uses Small and Large.
HI uses the others.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contain Group Lookup</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reset_Account_Team__c.field-meta.xml
<CustomField>
    <fullName>Reset_Account_Team__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reset Account Team</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Accounts</description>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner Accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>New Prospect Accounts</description>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Account_Team_Assignment__c/Account_Team_Assignment__c.object-meta.xml
<CustomObject>
    <description>This object will be used to save rules used to insert Business Entity teams.</description>
    <label>Account Team Assignment</label>
    <nameField>
        <displayFormat>ATA-{0000}</displayFormat>
        <label>Account Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Team_Assignment__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipName>Account_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <description>Values in this picklist must exactly match values in the Account Team role picklist, or the trigger to assign account team will fail.</description>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>AM Management</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Sales Management</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/Account_Team_Assignment_Additional_Rule__c.object-meta.xml
<CustomObject>
    <label>Account Team Assignment Additional Rules</label>
    <nameField>
        <displayFormat>ATAAR-{0000}</displayFormat>
        <label>Account Team Assignment Additional Rules</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Assignment Additional Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Blue_Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Blue_Partner_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blue Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Assignment Additional Rules</relationshipLabel>
    <relationshipName>Account_Team_Assignment_Additional_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Group_Size_Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Lower_Limit__c</fullName>
    <label>Group Size Lower Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Group_Size_Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Upper_Limit__c</fullName>
    <label>Group Size Upper Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Have_Asset__c.field-meta.xml
<CustomField>
    <fullName>Have_Asset__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Have Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Key_Client__c.field-meta.xml
<CustomField>
    <fullName>Key_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Client</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Additional_Rule__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Assignment_Additional_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Exception__c/Account_Team_Assignment_Exception__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting holds the exception scenarios for account team assignment

The logic for the custom setting can be read like this: &#39;Match the Partner_Id__c, check the Value in the Account_field__c, and if there is a match, do not assign the Team_Role__c.&#39;
Example for row AM-Medical: &#39;If the partner id is for BCBS Florida, and the Account.LSV_Business__c field = &#39;Medical Only&#39;, then do not assign the Team Role of &#39;AccountManager&#39;.</description>
    <label>Account Team Assignment Exception</label>
</CustomObject>

unpackaged/main/default/objects/Account_Team_Assignment_Exception__c/fields/Account_field__c.field-meta.xml
<CustomField>
    <fullName>Account_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Exception__c/fields/Do_Not_Assign__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Assign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Assign</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Exception__c/fields/Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Partner_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Team_Assignment_Exception__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Team Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This information contains Role Picklist information</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Benefit Manager</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Book Keeper</fullName>
            </value>
            <value>
                <fullName>Group Contact</fullName>
            </value>
            <value>
                <fullName>Regional VP</fullName>
            </value>
            <value>
                <fullName>Writing Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Agents working for agency</description>
    <label>Agent</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LSV_Group_Size__c.field-meta.xml
<CustomField>
    <fullName>LSV_Group_Size__c</fullName>
    <formula>Account.LSV_Group_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LSV Group Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Opportunity Sales Process</businessProcess>
    <description>This handles both sales renewal process</description>
    <label>Sales</label>
</RecordType>

unpackaged/main/default/globalValueSets/Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>Large</fullName>
    </customValue>
    <customValue>
        <fullName>CRG</fullName>
    </customValue>
    <customValue>
        <fullName>ACA</fullName>
    </customValue>
    <customValue>
        <fullName>MRG</fullName>
    </customValue>
    <customValue>
        <fullName>ASO/AFM</fullName>
    </customValue>
    <customValue>
        <fullName>RRG</fullName>
    </customValue>
    <customValue>
        <fullName>State</fullName>
    </customValue>
    <customValue>
        <fullName>FED</fullName>
    </customValue>
    <customValue>
        <fullName>Mid Market</fullName>
        <isActive>false</isActive>
        <label>Mid Market</label>
    </customValue>
    <customValue>
        <fullName>Large Market</fullName>
        <isActive>false</isActive>
        <label>Large Market</label>
    </customValue>
    <customValue>
        <fullName>Small Market</fullName>
        <isActive>false</isActive>
        <label>Small Market</label>
    </customValue>
    <description>Contains the picklist values for segment.</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountTrgTest.cls
/*
Name        : AccountTrgTest
Author      : Munazza Ahmed
Date        : 8/5/2016
Purpose : Test class for coverage of trigger on Account.
*/
@isTest
private class AccountTrgTest
{  
    
    public static testMethod void createAccountTeamTest()
    {
        Test.startTest();
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        id pId = [SELECT Id
                  FROM Profile
                  WHERE Name = 'USAble Standard Sales User' Limit 1].Id;
        //insert user
        User user_std = [SELECT id
                         FROM User
                         WHERE profileId =: pId AND IsActive = true limit 1];
        
        //insert account team assignment for blue territory method
        string accountManager = 'Account Manager';
        string BC_Code_1 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_1 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, accountManager, BC_Code_1);
        insert teamAssignmentBlueTerritory_1;
          
        //insert account team assignment for blue territory method
        string salesSupport_1 = 'Sales Support';
        string BC_Code_2 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_2 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, salesSupport_1, BC_Code_2);
        insert teamAssignmentBlueTerritory_2;  
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        //insert account team assignment for market segment & county method
        string salesExecutive = 'Sales Executive';
        string Segment_1 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_1 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesExecutive, countyTest.Id,Segment_1);
        insert teamAssignmentCounty_1;
        
        //insert account team assignment for market segment & county method
        string salesSupport_2 = 'Sales Support';
        string Segment_2 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_2 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesSupport_2, countyTest.Id,Segment_2);
        insert teamAssignmentCounty_2;
        
        //create account of master group recordtype
        id MasterGroupRTId;
        List<Recordtype> ListOfAccRt = [SELECT Name, Id
                                    FROM Recordtype
                                    WHERE Sobjecttype = 'Account'];
        for(recordtype rt : ListOfAccRt)
        {
            if(rt.Name == 'Master Group')
            {
                MasterGroupRTId = rt.id;
            }
        }
        //insert master account
        Account acc = new Account();
        acc.recordtypeid = MasterGroupRTId;
        acc.Name = 'Test Account Master Group';
        acc.Type = 'Master Group';
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        acc.LSV_Group_Size__c = 11;
        insert acc;
        
        Asset ast = USAbleUtility.createAsset(acc.Id);
        insert ast;
        
        Account_Team_Assignment_Additional_Rule__c ataar = new Account_Team_Assignment_Additional_Rule__c();
        ataar.Active__c = true;
        ataar.Blue_Partner_Id__c = acc_partner.Id;
        ataar.Group_Size_Lower_Limit__c = 1;
        ataar.Group_Size_Upper_Limit__c = 1000000;
        ataar.Have_Asset__c = 'STD|Dental|Life & ADD|LTD|VGTL|Worksite|Medical|GRP LIFE';
        ataar.Key_Client__c = false;
        ataar.Override__c = false;
        ataar.Role__c = 'Account Manager';
        ataar.User_Id__c = user_std.Id;
        insert ataar;
        
         //create account of master group recordtype
        id ProspectRTId;
        List<Recordtype> ListOfAccRt2 = [SELECT Name, Id
                                    FROM Recordtype
                                    WHERE Sobjecttype = 'Account'];
        for(recordtype rt : ListOfAccRt2)
        {
            if(rt.Name == 'Prospect')
            {
                ProspectRTId = rt.id;
            }
        }
        
        //insert Prospect account
        Account acc2 = new Account();
        acc2.recordtypeid = ProspectRTId;
        acc2.Name = 'Test Account Prospect';
        acc2.Type = 'Prospect';
        acc2.Partner__c = acc_partner.Id;
        acc2.Blue_Territory_Code__c = BC_Code_1 ;
        acc2.Market_Segment__c = Segment_1;
        acc2.County__c = countyTest.Id;
        acc2.LSV_Group_Size__c = 11;
        acc2.BillingCity = 'Taxes';
        acc2.BillingState = 'FL';
        acc2.BillingPostalCode = '123';
        acc2.BillingCountry = 'US';
        acc2.BillingStreet = '27';
        insert acc2;
        
        //insert custom setting record
        Account_Team_Assignment_Exception__c ex = new Account_Team_Assignment_Exception__c();
        ex.Name = 'Test exception';
        ex.Active__c = true;
        ex.Account_field__c = 'LSV_Business__c';
        ex.Do_Not_Assign__c = true;
        ex.Partner_Id__c = acc_partner.Id;
        ex.Team_Role__c = 'Account Manager';
        ex.Value__c = 'Medical Only';
        insert ex;
        
        acc.LSV_Business__c = 'Medical Only';
        update acc;
        
        acc.Blue_Territory_Code__c = BC_Code_2;
        acc.reset_account_team__c = true;
        update acc;
        
        Test.stopTest();
    } 
    
    public static testMethod void createATAAROverideTrueTest2()
    {
        Test.startTest();
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        id pId = [SELECT Id
                  FROM Profile
                  WHERE Name = 'USAble Standard Sales User' Limit 1].Id;
        //insert user
        User user_std = [SELECT id
                         FROM User
                         WHERE profileId =: pId AND IsActive = true limit 1];
        
        //insert account team assignment for blue territory method
        string accountManager = 'Account Manager';
        string BC_Code_1 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_1 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, accountManager, BC_Code_1);
        insert teamAssignmentBlueTerritory_1;
          
        //insert account team assignment for blue territory method
        string salesSupport_1 = 'Sales Support';
        string BC_Code_2 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_2 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, salesSupport_1, BC_Code_2);
        insert teamAssignmentBlueTerritory_2;  
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        //insert account team assignment for market segment & county method
        string salesExecutive = 'Sales Executive';
        string Segment_1 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_1 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesExecutive, countyTest.Id,Segment_1);
        insert teamAssignmentCounty_1;
        
        //insert account team assignment for market segment & county method
        string salesSupport_2 = 'Sales Support';
        string Segment_2 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_2 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesSupport_2, countyTest.Id,Segment_2);
        insert teamAssignmentCounty_2;
        
        //create account of master group recordtype
        id MasterGroupRTId;
        List<Recordtype> ListOfAccRt = [SELECT Name, Id
                                    FROM Recordtype
                                    WHERE Sobjecttype = 'Account'];
        for(recordtype rt : ListOfAccRt)
        {
            if(rt.Name == 'Master Group')
            {
                MasterGroupRTId = rt.id;
            }
        }
        //insert master account
        Account acc = new Account();
        acc.recordtypeid = MasterGroupRTId;
        acc.Name = 'Test Account Master Group';
        acc.Type = 'Master Group';
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        acc.LSV_Group_Size__c = 11;
        insert acc;
        
        Asset ast = USAbleUtility.createAsset(acc.Id);
        insert ast;
        
        Account_Team_Assignment_Additional_Rule__c ataar = new Account_Team_Assignment_Additional_Rule__c();
        ataar.Active__c = true;
        ataar.Blue_Partner_Id__c = acc_partner.Id;
        ataar.Group_Size_Lower_Limit__c = 1;
        ataar.Group_Size_Upper_Limit__c = 1000000;
        ataar.Have_Asset__c = 'STD|Dental|Life & ADD|LTD|VGTL|Worksite|Medical|GRP LIFE';
        ataar.Key_Client__c = false;
        ataar.Override__c = true;
        ataar.Role__c = 'Account Manager';
        ataar.User_Id__c = user_std.Id;
        insert ataar;
        
    
        //insert custom setting record
        Account_Team_Assignment_Exception__c ex = new Account_Team_Assignment_Exception__c();
        ex.Name = 'Test exception';
        ex.Active__c = true;
        ex.Account_field__c = 'LSV_Business__c';
        ex.Do_Not_Assign__c = true;
        ex.Partner_Id__c = acc_partner.Id;
        ex.Team_Role__c = 'Account Manager';
        ex.Value__c = 'Medical Only';
        insert ex;
        
        //acc.LSV_Business__c = 'Medical Only';
        //update acc;
        
        acc.Blue_Territory_Code__c = BC_Code_2;
        acc.reset_account_team__c = true;
        update acc;
        
        Test.stopTest();
    }  
    
    public static testMethod void createAccountTeamWithNoExTest()
    {
        Test.startTest();
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        id pId = [SELECT Id
                  FROM Profile
                  WHERE Name = 'USAble Standard Sales User' Limit 1].Id;
        //insert user
        User user_std = [SELECT id
                         FROM User
                         WHERE profileId =: pId AND IsActive = true limit 1];
        
        //insert account team assignment for blue territory method
        string accountManager = 'Account Manager';
        string BC_Code_1 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_1 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, accountManager, BC_Code_1);
        insert teamAssignmentBlueTerritory_1;
          
        //insert account team assignment for blue territory method
        string salesSupport_1 = 'Sales Support';
        string BC_Code_2 = 'A008';
        Account_Team_Assignment__c teamAssignmentBlueTerritory_2 = USAbleUtility.CreateAccountTeamAssignmentBlueTerritory(acc_partner.Id, user_std.Id, salesSupport_1, BC_Code_2);
        insert teamAssignmentBlueTerritory_2;  
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        //insert account team assignment for market segment & county method
        string salesExecutive = 'Sales Executive';
        string Segment_1 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_1 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesExecutive, countyTest.Id,Segment_1);
        insert teamAssignmentCounty_1;
        
        //insert account team assignment for market segment & county method
        string salesSupport_2 = 'Sales Support';
        string Segment_2 = 'Mid-Market';
        Account_Team_Assignment__c teamAssignmentCounty_2 = USAbleUtility.CreateAccountTeamAssignmentSegmentCounty(acc_partner.Id, user_std.Id, salesSupport_2, countyTest.Id,Segment_2);
        insert teamAssignmentCounty_2;
        
        //create account of master group recordtype
        id MasterGroupRTId;
        List<Recordtype> ListOfAccRt = [SELECT Name, Id
                                    FROM Recordtype
                                    WHERE Sobjecttype = 'Account'];
        for(recordtype rt : ListOfAccRt)
        {
            if(rt.Name == 'Master Group')
            {
                MasterGroupRTId = rt.id;
            }
        }
        //insert master account
        Account acc = new Account();
        acc.recordtypeid = MasterGroupRTId;
        acc.Name = 'Test Account Master Group';
        acc.Type = 'Master Group';
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        acc.LSV_Group_Size__c = 11;
        insert acc;
        
        Asset ast = USAbleUtility.createAsset(acc.Id);
        insert ast;
        
        Account_Team_Assignment_Additional_Rule__c ataar = new Account_Team_Assignment_Additional_Rule__c();
        ataar.Active__c = true;
        ataar.Blue_Partner_Id__c = acc_partner.Id;
        ataar.Group_Size_Lower_Limit__c = 1;
        ataar.Group_Size_Upper_Limit__c = 1000000;
        ataar.Have_Asset__c = 'STD|Dental|Life & ADD|LTD|VGTL|Worksite|Medical|GRP LIFE';
        ataar.Key_Client__c = false;
        ataar.Override__c = true;
        ataar.Role__c = 'Account Manager';
        ataar.User_Id__c = user_std.Id;
        insert ataar;
        
    
        //insert custom setting record
        /*
        Account_Team_Assignment_Exception__c ex = new Account_Team_Assignment_Exception__c();
        ex.Name = 'Test exception';
        ex.Active__c = true;
        ex.Account_field__c = 'LSV_Business__c';
        ex.Do_Not_Assign__c = true;
        ex.Partner_Id__c = acc_partner.Id;
        ex.Team_Role__c = 'Account Manager';
        ex.Value__c = 'Medical Only';
        insert ex;
        */
        //acc.LSV_Business__c = 'Medical Only';
        //update acc;
        
        acc.Blue_Territory_Code__c = BC_Code_2;
        acc.reset_account_team__c = true;
        update acc;
        
        Test.stopTest();
    }    
    
    public static testMethod void prospectAcctTest()
    {
        Test.startTest();
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;        
        
        Test.stopTest();
    }
    
    public static testMethod void ProspectToMGAccountTest()
    {
        Test.startTest();
        
        //insert Master Group Account
        Account acc_MG = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        insert acc_MG;
        
        //insert Master Group Account
        //Account acc_MG1 = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        //insert acc_MG1;
        
        //insert Prospect Account
        Account acc_Prospect = USAbleUtility.CreateProspectAccount(); //account returned from utility class
        insert acc_Prospect;
        
        //insert Oppotunity
        Opportunity NewOpp = USAbleUtility.CreateOpportunity(acc_Prospect);
        NewOpp.Effective_Date__c = date.today();
        insert NewOpp;
        
        //insert Contact
        Contact con = new contact();
        con.AccountId = acc_Prospect.id;
        con.FirstName = 'Clark';
        con.LastName  = 'Michael';
        con.Email = 'abc@test.com';
        con.Contact_Type__c = 'Group Contact';
        con.Phone = '1234567';
        con.Title = 'Mr.';
        con.Partner_Rep_Territory_Code__c = 'A555';
        con.MailingState = 'FL';  
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        
        
        insert con;
        
        
        acc_Prospect.Master_Group__c = acc_MG.id;
        update acc_Prospect;
        
        //acc_Prospect.Master_Group__c = acc_MG1.id;
        //update acc_Prospect;
        
        Test.stopTest();
    }
    
    public static testMethod void updateAgency()
    {
        
        Test.startTest();
        
        List<Blue_Rep_Fields__c> listCS = new List<Blue_Rep_Fields__c>();
        
        Blue_Rep_Fields__c brf = new Blue_Rep_Fields__c();
        brf.Name = 'BCBS of Florida';
        brf.API_Name_of_field__c = 'FL__c';
        brf.Name_of_field__c = 'FL';
        brf.Partner_Id__c = '0016300000ORP1dAAH';
        listCS.add(brf);
        
        Blue_Rep_Fields__c brf2 = new Blue_Rep_Fields__c();
        brf2.Name = 'Arkansas BCBS';
        brf2.API_Name_of_field__c = 'AR__c';
        brf2.Name_of_field__c = 'AR';
        brf2.Partner_Id__c = '0016300000ORP1aAAH';
        listCS.add(brf2);

        insert listCS;     
        
        
        List<Recordtype> agencyRecordTypeId = [SELECT Name, Id
                                    FROM Recordtype
                                    WHERE Sobjecttype = 'Account' and DeveloperName = 'Agency' limit 1];

        Account acc = new Account();
        acc.recordtypeid = agencyRecordTypeId[0].Id;
        acc.Name = 'Test Account Service Agency';
        acc.Type = 'Agency';
        acc.BillingCity = 'Taxes';
        acc.BillingState = 'FL';
        acc.BillingPostalCode = '123';
        acc.BillingCountry = 'US';
        acc.BillingStreet = '27';
        insert acc;

        Account accBA = new Account();
        accBA.recordtypeid = agencyRecordTypeId[0].Id;
        accBA.Name = 'Test Account Agency';
        accBA.Type = 'Agency';
        accBA.BillingCity = 'Taxes';
        accBA.BillingState = 'FL';
        accBA.BillingPostalCode = '123';
        accBA.BillingCountry = 'US';
        accBA.BillingStreet = '27';
        accBA.Service_Master_Agency__c = acc.id;
        insert accBA;        
        
        Contact con = new contact();
        con.AccountId = acc.id;
        con.Agency_Branch__c = accBA.id;
        con.FirstName = 'Clark';
        con.LastName  = 'Michael';
        con.Email = 'abc@test.com';
        con.Contact_Type__c = 'Agency';
        con.Phone = '1234567';
        con.Title = 'Mr.';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        insert con;  
        
        accBA.FL__c = true;
        update accBA;
        
        Test.stopTest();
    }
    
}