unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(TEXT(Group_Termination_Date__c) =  null,True,IF(Group_Termination_Date__c &gt;  TODAY(), True,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AR__c.field-meta.xml
<CustomField>
    <fullName>AR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Group_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LSV_Group_Size__c.field-meta.xml
<CustomField>
    <fullName>LSV_Group_Size__c</fullName>
    <label>LSV Group Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Manually_Create_Opp__c.field-meta.xml
<CustomField>
    <fullName>Manually_Create_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is being used in Opportunity creation batch.</description>
    <label>Manually Create Opp</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Manually_Create_Opp_User__c.field-meta.xml
<CustomField>
    <fullName>Manually_Create_Opp_User__c</fullName>
    <description>This field is being used in Auto create Opportunity batch.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Manually Create Opp User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contain Group Lookup</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Run_Opp_Batch__c.field-meta.xml
<CustomField>
    <fullName>Run_Opp_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in batch that automatically creates opportunities.</description>
    <label>Create Opportunity?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <description>Values in these three picklists should generally align, except Asset has a value for &#39;Medical&#39; not present in the other picklists: 
• Asset.Carrier__c 
• OpportunityProduct.Current_Carrier__c
• OpportunityProduct.Competitor_Name__c</description>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Hartford</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Lincoln National</fullName>
            </value>
            <value>
                <fullName>LSV</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Mutual of Omaha</fullName>
            </value>
            <value>
                <fullName>Pacific Guardian Life</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Protective</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Reliance Standard</fullName>
            </value>
            <value>
                <fullName>Soltice</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Sun Life</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Unum</fullName>
            </value>
            <value>
                <fullName>USAble</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Master_Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Master_Group_Anniversary_Date__c</fullName>
    <description>Populated via workflow rule from the Master Group Anniversary Date when the Asset Renewal Date is greater than or equal to the Master Group Anniversary Date. 
WFR: Asset Group Anniversary date
This is used for batch creating opportunities and for inventory reports.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Batch_Created__c.field-meta.xml
<CustomField>
    <fullName>Batch_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It indicates, if an opportunity has been auto created by the batch job. Used in batch that automatically creates opportunities</description>
    <label>Auto Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/FL__c.field-meta.xml
<CustomField>
    <fullName>FL__c</fullName>
    <formula>Account.FL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LSV_Group_Size__c.field-meta.xml
<CustomField>
    <fullName>LSV_Group_Size__c</fullName>
    <formula>Account.LSV_Group_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LSV Group Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Opportunity Sales Process</businessProcess>
    <description>This handles both sales renewal process</description>
    <label>Sales</label>
</RecordType>

unpackaged/main/default/objects/Opportunity_Batch__c/Opportunity_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will hold the opportunity batch parameters such as group size, Region or Partner.</description>
    <label>Opportunity Batch</label>
</CustomObject>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will mark if you want to run batch for this custom setting.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/API_Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>API_Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name of field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Blue_Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Blue_Partner_Id__c</fullName>
    <description>This filed will hold the blue partner Id.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Partner Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Group_Size_Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Lower_Limit__c</fullName>
    <description>This field is being used in the opportunity batch.</description>
    <label>Group Size Lower Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Group_Size_Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Upper_Limit__c</fullName>
    <description>This field will contain the group size limit for blue partner or region.</description>
    <label>Group Size Upper Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Months_In_Advance__c.field-meta.xml
<CustomField>
    <fullName>Months_In_Advance__c</fullName>
    <description>This field will used in batch as number of months in advance of the group anniv date.</description>
    <label>Months In Advance</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Number_of_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunities__c</fullName>
    <description>This field is being used in opportunity batch.</description>
    <label>Number of Opportunities</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASO / ATP STD</fullName>
            </value>
            <value>
                <fullName>Copay PPO</fullName>
            </value>
            <value>
                <fullName>Indiv. Dental</fullName>
            </value>
            <value>
                <fullName>Indiv. Life</fullName>
            </value>
            <value>
                <fullName>Indiv. Worksite</fullName>
            </value>
            <value>
                <fullName>Indemnity/PAR</fullName>
            </value>
            <value>
                <fullName>LTD / VLTD</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>PPO</fullName>
            </value>
            <value>
                <fullName>PPO+</fullName>
            </value>
            <value>
                <fullName>Prepaid/DHMO</fullName>
            </value>
            <value>
                <fullName>STD / VSTD</fullName>
            </value>
            <value>
                <fullName>TDI</fullName>
            </value>
            <value>
                <fullName>True Group Life</fullName>
            </value>
            <value>
                <fullName>VADD</fullName>
            </value>
            <value>
                <fullName>VGTL</fullName>
            </value>
            <value>
                <fullName>Worksite ECR</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Non-Integrated</fullName>
            </value>
            <value>
                <fullName>PFML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line_for_Opp__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_for_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used in the code that creates the opportunities via batch, and it indicates that the product is a &#39;generic&#39; product line that could be added to an opportunity.</description>
    <label>Product Line for Opp</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TestOppRenewalHeaderCreationBatch.cls
@isTest(SeeAllData=false)
Public Class TestOppRenewalHeaderCreationBatch{
    
    //@testSetup
    Public static testMethod void testData(){
        
        // Insert Custom Setting
        Opportunity_Batch__c NewCS = new Opportunity_Batch__c();
        NewCS.Name = 'FL';
        NewCS.Active__c = true;
        NewCS.API_Name_of_field__c = 'FL__c';
        NewCS.Group_Size_Lower_Limit__c = 50;
        NewCS.Group_Size_Upper_Limit__c = 300;
        NewCS.Blue_Partner_Id__c = '001i000000cN6g4';
        NewCS.Number_of_Opportunities__c = 1;
        NewCS.Months_In_Advance__c = 5;
        insert NewCS;
        
        /*
        // Insert Custom Setting for AR
        Opportunity_Batch__c NewCSAR = new Opportunity_Batch__c();
        NewCSAR.Name = 'AR';
        NewCSAR.Active__c = true;
        NewCSAR.API_Name_of_field__c = 'AR__c';
        NewCSAR.Group_Size_Lower_Limit__c = 20;
        NewCSAR.Group_Size_Upper_Limit__c = 5000;
        NewCSAR.Blue_Partner_Id__c = '001q000000eX3Ck';
        NewCSAR.Number_of_Opportunities__c = 1;
        insert NewCSAR;
        */
        
        //Insert Account For Florida
        Account Acc = new Account();
        Acc.name = 'Master Group Acc';
        Acc.Partner__c = '001i000000cN6g4';
        Acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        Acc.LSV_Group_Size__c = 220 ;
        Acc.FL__c = true;
        
        //date myDate = date.newInstance(2016, 11, 15);
        date myDate = date.today().addMonths(5);
        Acc.Group_Anniversary_Date__c = myDate;
        insert Acc;
        
        //insert Products
        List<Product2> lstProducts = new List<Product2>();
        
        Product2 p = new product2(name='x');
        lstProducts.add(p);
        
        Product2 p2 = new product2(name='y');
        p2.Product_Category__c = 'Medical';
        p2.IsActive = true;
        lstProducts.add(p2);
        
        insert lstProducts;
        
        
        //Insert Pricebook Entry
        PricebookEntry pbe = new PricebookEntry(pricebook2id=Test.getStandardPricebookId(), product2id=p.id,unitprice=1.0, isActive=true);
        insert pbe;
        
        //Insert Assets
        List<Asset> lstAssets = new List<Asset>();
        
        Asset Ast = new Asset ();
        Ast.Name = 'Ast1';
        Ast.Carrier__c = 'AIG';
        Ast.AccountId = Acc.Id;
        Ast.Product2Id = p2.Id;
        Ast.Master_Group_Anniversary_Date__c = myDate;
        Ast.Renewal_Date__c = date.today().addDays(1);
        lstAssets.add(Ast);
        
        insert lstAssets;

        /*
        //Insert Account For Arkansas
        Account AccAR = new Account();
        AccAR.name = 'Master Group Acc';
        AccAR.Partner__c = '001q000000eX3Ck';
        AccAR.RecordTypeId = '012i0000001I8XYAA0';
        AccAR.LSV_Group_Size__c = 220 ;
        AccAR.AR__c = true;
        
        //date myDate = date.newInstance(2016, 11, 15);
        date myDateAR = date.today().addMonths(5);
        AccAR.Group_Anniversary_Date__c = myDateAR;
        insert AccAR;
        
        //Insert Assets For Arkansas
        List<Asset> lstAssetsAR = new List<Asset>();
        
        Asset AstAR = new Asset ();
        AstAR.Name = 'Ast1';
        AstAR.Carrier__c = 'AIG';
        AstAR.AccountId = AccAR.Id;
        AstAR.Product2Id = p2.Id;
        AstAR.Master_Group_Anniversary_Date__c = myDateAR;
        AstAR.Renewal_Date__c = date.today().addDays(1);
        lstAssetsAR.add(AstAR);
        
        insert lstAssetsAR;
        */
        Test.startTest();
             
             OppRenewalBatch B = new OppRenewalBatch();
             database.executeBatch(b);
            
             Test.stopTest();
      
    }
    
    
    Public static testMethod void BatchTest(){
         
            // Insert Custom Setting for AR
            Opportunity_Batch__c NewCSAR = new Opportunity_Batch__c();
            NewCSAR.Name = 'AR';
            NewCSAR.Active__c = true;
            NewCSAR.API_Name_of_field__c = 'AR__c';
            NewCSAR.Group_Size_Lower_Limit__c = 20;
            NewCSAR.Group_Size_Upper_Limit__c = 5000;
            NewCSAR.Blue_Partner_Id__c = '001i000000cN6Id';
            NewCSAR.Number_of_Opportunities__c = 1;
            NewCSAR.Months_In_Advance__c = 5;
            insert NewCSAR; 
            
            //insert Products
            List<Product2> lstProducts = new List<Product2>();
            
            Product2 p = new product2(name='x');
            lstProducts.add(p);
            
            Product2 p2 = new product2(name='y');
            p2.Product_Category__c = 'Medical';
            p2.IsActive = true;
            lstProducts.add(p2);
            
            insert lstProducts;
            
            
            //Insert Pricebook Entry
            PricebookEntry pbe = new PricebookEntry(pricebook2id=Test.getStandardPricebookId(), product2id=p.id,unitprice=1.0, isActive=true);
            insert pbe;
        
            //Insert Account For Arkansas
            Account AccAR = new Account();
            AccAR.name = 'Master Group Acc';
            AccAR.Partner__c = '001i000000cN6Id';
            AccAR.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
            AccAR.LSV_Group_Size__c = 220 ;
            AccAR.AR__c = true;
            
            //date myDate = date.newInstance(2016, 11, 15);
            date myDateAR = date.today().addMonths(5);
            AccAR.Group_Anniversary_Date__c = myDateAR;
            insert AccAR;
            
            //Insert Assets For Arkansas
            List<Asset> lstAssetsAR = new List<Asset>();
            
            Asset AstAR = new Asset ();
            AstAR.Name = 'Ast1';
            AstAR.Carrier__c = 'AIG';
            AstAR.AccountId = AccAR.Id;
            AstAR.Product2Id = p2.Id;
            AstAR.Master_Group_Anniversary_Date__c = myDateAR;
            AstAR.Renewal_Date__c = date.today().addDays(1);
            lstAssetsAR.add(AstAR);
        
            insert lstAssetsAR;
        
            Test.startTest();
             
             OppRenewalBatch B = new OppRenewalBatch();
             database.executeBatch(b);
            
             Test.stopTest();

    } 
    
    Public static testMethod void BatchTestOLI(){
        
        
        //Insert Account For Florida
        Account Acc = new Account();
        Acc.name = 'Master Group Acc';
        Acc.Partner__c = '001i000000cN6g4';
        Acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        Acc.LSV_Group_Size__c = 220 ;
        Acc.FL__c = true;
        
        //date myDate = date.newInstance(2016, 11, 15);
        date myDate = date.today().addMonths(5);
        Acc.Group_Anniversary_Date__c = myDate;
        insert Acc;
        
        //insert Products
        List<Product2> lstProducts = new List<Product2>();
        
        Product2 p = new product2(name='x');
        lstProducts.add(p);
        
        Product2 p2 = new product2(name='y');
        p2.Product_Category__c = 'Medical';
        p2.IsActive = true;
        p2.Product_Line_for_Opp__c = true;
        lstProducts.add(p2);
        
        insert lstProducts;
        
        
        //Insert Pricebook Entry
        PricebookEntry pbe = new PricebookEntry(pricebook2id=Test.getStandardPricebookId(), product2id=p.id,unitprice=1.0, isActive=true);
        insert pbe;
        
        //Insert Assets
        List<Asset> lstAssets = new List<Asset>();
        
        Asset Ast = new Asset ();
        Ast.Name = 'Ast1';
        Ast.Carrier__c = 'AIG';
        Ast.AccountId = Acc.Id;
        Ast.Product2Id = p2.Id;
        Ast.Master_Group_Anniversary_Date__c = myDate;
        Ast.Renewal_Date__c = date.today().addDays(1);
        lstAssets.add(Ast);
        
        insert lstAssets;

        Opportunity Opp = new Opportunity();
        Opp.Name = 'Test Opp';
        Opp.AccountId = Acc.Id;
        Opp.Batch_Created__c = true;
        Opp.Type = 'New Business';
        Opp.StageName = 'New';
        DateTime nn = datetime.now();
        Opp.CloseDate = nn.date();
        Opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opp.Effective_Date__c = nn.date();
        insert Opp;
        
        Map <Id,Set<Id>> mapAccountAssets = new map<Id,Set<Id>>();
        Set <Id> SetofId = new Set <Id>();
        Set <Id> SetofOppId = new Set <Id>();
        SetofOppId.add(Opp.Id);
        mapAccountAssets.put(Acc.Id, SetofId);
         Test.startTest();
         
         String cron = '';
                 DateTime n = datetime.now().addMinutes(1);
                 //cron += n.millisecond();
                 cron += n.second();
                 cron += ' ' + n.minute();
                 cron += ' ' + n.hour();
                 cron += ' ' + n.day();
                 cron += ' ' + n.month();
                 cron += ' ' + '?';
                 cron += ' ' + n.year();                 
            System.schedule('Batch Create OLI_'+n, cron, new Sch_OppRenewalLineItemCreationBatch(SetofOppId, mapAccountAssets));
        
         Test.stopTest(); 
    }
    
     Public static testMethod void BatchTestMethodOppBatchInvoke(){
         
         //Insert Account For Florida
         Account Acc = new Account();
         Acc.name = 'Master Group Acc';
         Acc.Partner__c = '001i000000cN6g4';
         Acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
         Acc.LSV_Group_Size__c = 220 ;
         Acc.FL__c = true;
         Acc.Manually_Create_Opp_User__c = '005i0000002OG7PAAW';
         
         //date myDate = date.newInstance(2016, 11, 15);
         date myDate = date.today().addMonths(5);
         Acc.Group_Anniversary_Date__c = myDate;
         Acc.Run_Opp_Batch__c = true;
         Acc.Manually_Create_Opp__c = true;
         insert Acc;
         
         List <Id> lstAccId = new List <Id>();
         lstAccId.add(Acc.Id);
         /*
         Test.startTest();
         Opp_Batch_Invoceable.getAccountNames(lstAccId);         
         Test.stopTest();
			*/
     }
    
    Public Static TestMethod void TestMethodSchOppRenewal(){
        
        
         String cron = '';
                 DateTime n = datetime.now().addMinutes(2);
                 //cron += n.millisecond();
                 cron += n.second();
                 cron += ' ' + n.minute();
                 cron += ' ' + n.hour();
                 cron += ' ' + n.day();
                 cron += ' ' + n.month();
                 cron += ' ' + '?';
                 cron += ' ' + n.year();                                    
         system.schedule('Job Name', cron, new Sch_OppRenewalBatch());
         //Sch_OppRenewalBatch ScOp = new Sch_OppRenewalBatch();
        
    }        
    
}