unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(TEXT(Group_Termination_Date__c) =  null,True,IF(Group_Termination_Date__c &gt;  TODAY(), True,false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AR__c.field-meta.xml
<CustomField>
    <fullName>AR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Group_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Master_Group.recordType-meta.xml
<RecordType>
    <fullName>Master_Group</fullName>
    <active>true</active>
    <description>Master Group Records</description>
    <label>Master Group</label>
</RecordType>

unpackaged/main/default/objects/Opportunity_Batch__c/Opportunity_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will hold the opportunity batch parameters such as group size, Region or Partner.</description>
    <label>Opportunity Batch</label>
</CustomObject>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will mark if you want to run batch for this custom setting.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/API_Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>API_Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name of field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Blue_Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Blue_Partner_Id__c</fullName>
    <description>This filed will hold the blue partner Id.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Partner Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Group_Size_Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Lower_Limit__c</fullName>
    <description>This field is being used in the opportunity batch.</description>
    <label>Group Size Lower Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Group_Size_Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Group_Size_Upper_Limit__c</fullName>
    <description>This field will contain the group size limit for blue partner or region.</description>
    <label>Group Size Upper Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Months_In_Advance__c.field-meta.xml
<CustomField>
    <fullName>Months_In_Advance__c</fullName>
    <description>This field will used in batch as number of months in advance of the group anniv date.</description>
    <label>Months In Advance</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity_Batch__c/fields/Number_of_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Opportunities__c</fullName>
    <description>This field is being used in opportunity batch.</description>
    <label>Number of Opportunities</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/OppRenewalBatch.cls
global without sharing class OppRenewalBatch implements Database.Batchable<sObject>, Database.stateful {
    final List<Id> AccId = new List <Id>();
    global Map <String, Opportunity_Batch__c> MapofRegionAndCS;
    global OppRenewalBatch(){
        system.debug('Without List Constructor');
    }
    global OppRenewalBatch(List <Id> lstAccId){
        AccId = lstAccId;
    }
    
    global Database.QueryLocator start (Database.BatchableContext BC){
        string Query;
        string CustomSettingQuery;
        string AccountId;
        //Map <String, Opportunity_Batch__c> MapofRegionAndCS = new Map <String, Opportunity_Batch__c>();
        
        if(AccId.size() > 0)
        {    
            // Querying the required data set
            Id AcId = AccId[0];
            Query = 'SELECT ID, Group_Anniversary_Date__c FROM Account Where Account.Id ='+AcId;
            system.debug('Query '+Query);
        }
        else{
            
            // Querying the required data set
            //Query = 'SELECT ID, Group_Anniversary_Date__c FROM Account Where Account.RecordType.DeveloperName = \'Master_Group\' AND Aniv_prior_four_months__c= TRUE';
            //system.debug('Query2 '+Query);
            
            // Zaid New Dynamic Functionality starts heres
            //CustomSettingQuery = 'SELECT ID, API_Name_of_field__c,    Blue_Partner_Id__c, AR__c, FL__c, Group_Size_Lower_Limit__c, Group_Size_Upper_Limit__c, HI__c, Number_of_Opportunities__c    FROM Opportunity_Batch__c  ';
            CustomSettingQuery = 'SELECT ID, API_Name_of_field__c,  Blue_Partner_Id__c, Group_Size_Lower_Limit__c, Group_Size_Upper_Limit__c, Number_of_Opportunities__c, Months_In_Advance__c    FROM Opportunity_Batch__c  WHERE Active__c = TRUE ';
            
            system.debug('Opp_AnniversaryDateBatch'+CustomSettingQuery );
        }
        
        return Database.getQueryLocator(CustomSettingQuery);
    
    
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity_Batch__c> lst_OppBatch){
        
         List <Opportunity_Batch__c> lst_OppBatchToSend = new List <Opportunity_Batch__c>();
         MapofRegionAndCS = new Map <String, Opportunity_Batch__c>();
         system.debug('list here in execute '+lst_OppBatch);
         for (Opportunity_Batch__c OppBatch : lst_OppBatch)
         {
             
             lst_OppBatchToSend.add(OppBatch); 
             MapofRegionAndCS.put(OppBatch.API_Name_of_field__c, OppBatch);
             //Database.executeBatch(new Opp_AnniversaryDateBatch_FetchAccounts(OppBatch.API_Name_of_field__c, OppBatch), 200);
             
         }
         system.debug('Map '+MapofRegionAndCS);
        
    }
    global void finish(Database.BatchableContext BC){
        for (String strReg : MapofRegionAndCS.keySet())
        {
            DateTime n = datetime.now().addMinutes(1);
             String cron = '';
             
             cron += n.second();
             cron += ' ' + n.minute();
             cron += ' ' + n.hour();
             cron += ' ' + n.day();
             cron += ' ' + n.month();
             cron += ' ' + '?';
             cron += ' ' + n.year();
             
             System.Debug('ah::MapofRegionAndCS Months_In_Advance__c ' + MapofRegionAndCS.get(strReg).Months_In_Advance__c);
            
             System.schedule('Schedule_OppHeader_'+strReg.replace('__c','')+'_'+n, cron, new Sch_OppRenewalHeaderCreationBatch(strReg, MapofRegionAndCS.get(strReg)));
            
        }
    }

}