unpackaged/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>BillingStreet + BillingCity + BillingState + BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Blue_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Blue_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blue Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Blue Rep Name must be a contact with record type of Partner Rep whose account is the same as the Partner account</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Rep</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partner__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contain Group Lookup</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Other Accounts</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner Accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Agency_Partner__c/Agency_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction to show many-to-many relationship between Agency and Blue Cross Partner</description>
    <label>Agency/Partner</label>
    <nameField>
        <displayFormat>AP-{000}</displayFormat>
        <label>Agency/Partner Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies/Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agency_Partner__c/fields/Master_Agency_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Agency_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Master Agency ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Blue Partner</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Agency_Partner__c/fields/Master_Partner_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Partner_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Master Partner ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Agencies</relationshipLabel>
    <relationshipName>Blue_Partner</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Blue_Rep_Fields__c/Blue_Rep_Fields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Indicates the relationship of the Blue Partner SFID to a State/Region field on Account/Contact. The logic can be read like this: &#39;When an agency/partner relationship is created, find the Partner Id in the custom setting and then update the field indicated in API_Name_of_field__c to TRUE. Update the field on both the Agency record and its contact records.&quot;</description>
    <label>Blue Partner Fields for Sharing</label>
</CustomObject>

unpackaged/main/default/objects/Blue_Rep_Fields__c/fields/API_Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>API_Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name of field</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blue_Rep_Fields__c/fields/Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of field</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>This field contains Contact type Pick list value</description>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Group Contact</fullName>
            </value>
            <value>
                <fullName>Medical Service Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Partner Rep</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Authorized Rep/POA</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Enrollment Contact</fullName>
            </value>
            <value>
                <fullName>Funeral Home</fullName>
            </value>
            <value>
                <fullName>Health Provider</fullName>
            </value>
            <value>
                <fullName>Other Business Entity Contact</fullName>
            </value>
            <value>
                <fullName>Other Service Provider</fullName>
            </value>
            <value>
                <fullName>Carrier Contact</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Student Child</fullName>
            </value>
            <value>
                <fullName>Domestic Partner</fullName>
            </value>
            <value>
                <fullName>Disabled Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FL__c.field-meta.xml
<CustomField>
    <fullName>FL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_Director__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep Director)</relationshipLabel>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep Manager)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_VP__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep VP</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep VP)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Agents working for agency</description>
    <label>Agent</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Other service contacts</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/ETL_and_Non_ETL_fields_for_Contact__c/ETL_and_Non_ETL_fields_for_Contact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains all etl and non-etl fields of contact.</description>
    <label>ETL and Non-ETL fields for Contact</label>
</CustomObject>

unpackaged/main/default/objects/ETL_and_Non_ETL_fields_for_Contact__c/fields/ETL__c.field-meta.xml
<CustomField>
    <fullName>ETL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ETL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ETL_and_Non_ETL_fields_for_Contact__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field API Name</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/FL__c.field-meta.xml
<CustomField>
    <fullName>FL__c</fullName>
    <formula>Account.FL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Director__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep Director)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep Manager)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Rep Territory Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_VP__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep VP</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep VP)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Changed_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Changed_Carrier__c</fullName>
    <inlineHelpText>Did the group stay with the same carrier or change carrier?</inlineHelpText>
    <label>Changed Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don’t Know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/OpportunityTriggerTest.cls
/*
Name        : OpportunityTriggerTest
Author      : Munazza Ahmed
Date        : 7/19/2016
Purpose : Test class for coverage of trigger on Opportunity.

Modified By: Zaid Ali
Date: 8/15/2016
Purpose: To get coverage of Opportunity heiarchy fields populate.
*/

@isTest

private class OpportunityTriggerTest
{  
    
    public static testMethod void assetCreationOnOppCloseTest()
    {
        Test.startTest();
        //insert account
        Account acc = new Account();
        acc = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        insert acc;
        //insert Opportunity
        Opportunity opp = new Opportunity();
        opp = USAbleUtility.CreateOpportunity(acc); //opportunity returned from utility class
        opp.Effective_Date__c = date.today();
        insert opp;
        //insert Product
        Product2 prd = new Product2();
        prd = USAbleUtility.CreateProuct(); //Product returned from utility class
        insert prd;
        //insert PricebookEntry
        PricebookEntry pbe = new PricebookEntry();
        pbe = USAbleUtility.CreatePBE(prd); //PricebookEntry returned from utility class
        insert pbe;
        //insert OpportunityLineItem with closed lost stage
        OpportunityLineItem oli1 = new OpportunityLineItem();
        oli1 = USAbleUtility.CreateOppLineItemClosedLost(opp,prd,pbe); //OpportunityLineItem returned from utility class
        oli1.UnitPrice = 1;
        oli1.Changed_Carrier__c = 'yes';        
        insert oli1;
        //insert OpportunityLineItem with other than closed lost stage
        OpportunityLineItem oli2 = new OpportunityLineItem();
        oli2 = USAbleUtility.CreateOppLinePursue(opp,prd,pbe); //OpportunityLineItem returned from utility class
        oli2.UnitPrice = 2;
        insert oli2;
        opp.stagename = 'Closed Lost';
        update opp;
        
        Test.stopTest();
    }  
    
    //added by Zaid Ali 
    public static testMethod void OppHeararchyTest()
    {
        Test.startTest();
        
        /*
        // partner rep functionality test here
        Account AccPR = new Account();
        AccPR = USAbleUtility.CreateMasterGroupAccount();
        AccPR.BillingStreet = 'asd';
        AccPR.BillingCity = 'asd';
        AccPR.BillingState = 'asd';
        AccPR.BillingCountry = 'asd';
        AccPR.BillingPostalCode = '123';
        AccPR.Blue_Rep_Name__c = Conclone.Id
        insert AccPR;
        */
        
        Account AccAgency = New Account();
        AccAgency = USAbleUtility.CreateAgencyAccount();
        AccAgency.BillingStreet = 'asd';
        AccAgency.BillingCity = 'asd';
        AccAgency.BillingState = 'asd';
        AccAgency.BillingCountry = 'asd';
        AccAgency.BillingPostalCode = '123';
        insert AccAgency ;
        
        
        Account AccForPartner = new Account();
        AccForPartner = USAbleUtility.CreatePartnerAccount();
        //AccForPartner.Address__c='asdad';
        AccForPartner.BillingStreet = 'asd';
        AccForPartner.BillingCity = 'asd';
        AccForPartner.BillingState = 'asd';
        AccForPartner.BillingCountry = 'asd';
        AccforPartner.BillingPostalCode = '123';
        insert AccForPartner;                        
        
        Id RecordTypeIdPR = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Partner Rep').getRecordTypeId();
        Id RecordTypeIdAgent = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Id RecordTypeIdGroup = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        
        Contact Con = new Contact ();
        Con.LastName = 'Test';
        Con.FirstName = 'Test';
        Con.AccountId = AccForPartner.Id;
        Con.RecordtypeId = RecordTypeIdPR ;
        insert Con;
        
        Contact Conclone = new Contact ();
        Conclone.LastName = 'Test';
        Conclone.FirstName = 'Test';
        Conclone.AccountId = AccForPartner.Id;
        Conclone.RecordtypeId = RecordTypeIdPR ;
        insert Conclone;
        
        Account AccPR = new Account();
        AccPR = USAbleUtility.CreateMasterGroupAccount();
        AccPR.BillingStreet = 'asd';
        AccPR.BillingCity = 'asd';
        AccPR.BillingState = 'asd';
        AccPR.BillingCountry = 'asd';
        AccPR.BillingPostalCode = '123';
        AccPR.Blue_Rep_Name__c = Conclone.Id;
        AccPR.Partner__c = AccForPartner.id;
            insert AccPR;        
        
        Contact Con1 = new Contact ();
        Con1.LastName = 'Test1';
        Con1.FirstName = 'First Name';
        Con1.AccountId = AccAgency.Id;
        Con1.RecordtypeId = RecordTypeIdAgent;
        Con1.Phone = '123';
        Con1.Email = 'abc@gmail.com';
        Con1.Contact_Type__c = 'Agent';
        insert Con1;
        
        Contact Con2 = new Contact ();
        Con2.LastName = 'Test2';
        Con2.FirstName = 'First Name';
        Con2.AccountId = AccAgency.Id;
        Con2.RecordtypeId = RecordTypeIdAgent;
        Con2.Phone = '123';
        Con2.Email = 'abc@gmail.com';
        Con2.Contact_Type__c = 'Agent';
        insert Con2;
        
        Contact Con3 = new Contact ();
        Con3.LastName = 'Test3';
        Con3.FirstName = 'First Name';
        Con3.AccountId = AccPR.Id;
        Con3.Partner_Rep_Director__c = Con.Id;
        Con3.Partner_Rep_Manager__c = Con2.Id;
        Con3.Partner_Rep_VP__c = Con1.Id;
        Con3.Partner_Rep_Territory_Code__c = '123';
        Con3.RecordtypeId = RecordTypeIdGroup ;
        Con3.Phone = '123';
        Con3.Email = 'abc@gmail.com';
        Con3.Contact_Type__c = 'Agent';
        insert Con3;
        
        //AccPR.Blue_Rep_Name__c = Con.id;
        //update AccPr;
        
        Opportunity OppPR = new Opportunity();
        OppPR = USAbleUtility.CreateOpportunity(AccPR); //opportunity returned from utility class
        OppPR.StageName = 'In Process';
        OppPR.Effective_Date__c = date.today();
        insert OppPR;
        
        Con3.Partner_Rep_Manager__c = con.id;
        update con3;
         
        //List <Opportunity> lstOpp = new List <Opportunity>();
        //lstOpp.add(opp);
        //OpportunityTrgUtil.UpdateOpportunityReps(lstOpp);
        //
        Test.stopTest();
    }
    
    public static testMethod void ContactCustomSettingTest()
    {
        Test.startTest();
        
        Id RecordTypeIdAgent = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        
        Account acc = new Account();
        acc = USAbleUtility.CreateAgencyAccount(); //account returned from utility class
        insert acc;
        
        Account AccForPartner = new Account();
        AccForPartner = USAbleUtility.CreatePartnerAccount();
        //AccForPartner.Address__c='asdad';
        AccForPartner.BillingStreet = 'asd';
        AccForPartner.BillingCity = 'asd';
        AccForPartner.BillingState = 'asd';
        AccForPartner.BillingCountry = 'asd';
        AccforPartner.BillingPostalCode = '123';
        insert AccForPartner;
        
        Blue_Rep_Fields__c blueRepFields = new Blue_Rep_Fields__c();
        blueRepFields.API_Name_of_field__c = 'FL__c';
        blueRepFields.Partner_Id__c = AccForPartner.id;
        blueRepFields.Name_of_field__c = 'FL';
        blueRepFields.Name = 'Florida';
        insert blueRepFields;
        
        Agency_Partner__c AP = new Agency_Partner__c();
        AP.Master_Partner_ID__c = AccForPartner.id;
        AP.Master_Agency_ID__c = acc.id;
        insert AP;
        
        Contact Con1 = new Contact ();
        Con1.LastName = 'Test1';
        Con1.FirstName = 'First Name';
        Con1.AccountId = Acc.Id;
        Con1.RecordtypeId = RecordTypeIdAgent;
        Con1.Phone = '123';
        Con1.Email = 'abc@gmail.com';
        Con1.Contact_Type__c = 'Agent';
        insert Con1;
        
        // This code is added by Zaid for deployment
            ETL_and_Non_ETL_fields_for_Contact__c ETLFields = new ETL_and_Non_ETL_fields_for_Contact__c ();
            ETLFields.ETL__c = true;
            ETLFields.Field_API_Name__c = 'TestFieldAPIName';
            ETLFields.Name = 'Test';
        insert ETLFields;
        
        Con1.Email = 'abcd@gmail.com';
        update con1;
        // Zaid Code ends here
        // 
        Test.stopTest();
        
    }
    public static testMethod void OpportunityCreationBlueRepRegionPopulateTest()
    {
        Test.startTest();
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        //insert account
        Account acc = new Account();
        acc = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        acc.Partner__c = acc_partner.Id;
        insert acc;
        
        //insert custom setting record
        Blue_Rep_Fields__c bFields = new Blue_Rep_Fields__c ();
        bFields.Name = 'Test Field';
        bFields.Partner_Id__c = acc_partner.Id;
        bFields.API_Name_of_field__c = 'FL__c';
        bFields.Name_of_field__c = 'FL';
        insert bFields;
        
        //insert Opportunity
        Opportunity opp = new Opportunity();
        opp = USAbleUtility.CreateOpportunity(acc); //opportunity returned from utility class
        opp.Effective_Date__c = date.today();
        insert opp;
        
        Test.stopTest();
    }
}