unpackaged/main/default/objects/Account/fields/AR__c.field-meta.xml
<CustomField>
    <fullName>AR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner Accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Agency_Partner__c/Agency_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction to show many-to-many relationship between Agency and Blue Cross Partner</description>
    <label>Agency/Partner</label>
    <nameField>
        <displayFormat>AP-{000}</displayFormat>
        <label>Agency/Partner Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies/Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agency_Partner__c/fields/Master_Agency_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Agency_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Master Agency ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Blue Partner</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Agency_Partner__c/fields/Master_Partner_ID__c.field-meta.xml
<CustomField>
    <fullName>Master_Partner_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Master Partner ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Agencies</relationshipLabel>
    <relationshipName>Blue_Partner</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Blue_Rep_Fields__c/Blue_Rep_Fields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Indicates the relationship of the Blue Partner SFID to a State/Region field on Account/Contact. The logic can be read like this: &#39;When an agency/partner relationship is created, find the Partner Id in the custom setting and then update the field indicated in API_Name_of_field__c to TRUE. Update the field on both the Agency record and its contact records.&quot;</description>
    <label>Blue Partner Fields for Sharing</label>
</CustomObject>

unpackaged/main/default/objects/Blue_Rep_Fields__c/fields/API_Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>API_Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name of field</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blue_Rep_Fields__c/fields/Name_of_field__c.field-meta.xml
<CustomField>
    <fullName>Name_of_field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of field</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FL__c.field-meta.xml
<CustomField>
    <fullName>FL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FL</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Agents working for agency</description>
    <label>Agent</label>
</RecordType>

unpackaged/main/default/classes/AgencyPartnerTrgTest.cls
/*
Name        : AgencyPartnerTrgTest
Author      : Munazza Ahmed
Date        : 9/5/2016
Purpose : Test class for coverage of trigger on AgencyPartner.
*/
@isTest
private class AgencyPartnerTrgTest
{  
    public static testMethod void BlueRepRegionCheckboxesTest()
    {
        Test.startTest();
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        //insert account
        Account acc = new Account();
        acc = USAbleUtility.CreateAgencyAccount(); //account returned from utility class
        insert acc;
        
        string AgenctRTId;
        //query appropriate recordtype
        List<Recordtype> ListOfAccRt = [SELECT Name, Id
                                        FROM Recordtype
                                        WHERE Sobjecttype = 'Contact'];
        for(recordtype rt : ListOfAccRt)
        {
            if(rt.Name == 'Agent')
            {
                AgenctRTId = rt.id;
            }
        }
        /*
        //insert contact agent
        Contact cont = new contact();
        cont.FirstName = 'test';
        cont.LastName = 'agent';
        cont.AccountId = acc.Id;
        cont.Phone = '0213455';
        cont.Email = 'test@testmail.com';
        cont.RecordTypeId = AgenctRTId;
        insert cont;
        */
        //insert custom setting record
        Blue_Rep_Fields__c bFields = new Blue_Rep_Fields__c ();
        bFields.Name = 'Test Field';
        bFields.Partner_Id__c = acc_partner.Id;
        bFields.API_Name_of_field__c = 'FL__c';
        bFields.Name_of_field__c = 'FL';
        insert bFields;
        
        
        //insert AgencyPartner record
        Agency_Partner__c ap = new Agency_Partner__c();
        ap.Master_Agency_ID__c = acc.Id;
        ap.Master_Partner_ID__c = acc_partner.Id;
        insert ap;
        
        //insert partner account
        Account acc_partner_2 = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner_2;
        
        //insert custom setting record
        Blue_Rep_Fields__c bFields_2 = new Blue_Rep_Fields__c ();
        bFields_2.Name = 'Test Field2';
        bFields_2.Partner_Id__c = acc_partner_2.Id;
        bFields_2.API_Name_of_field__c = 'AR__c';
        bFields_2.Name_of_field__c = 'AR';
        insert bFields_2;
        
        //update AgencyPartner record
        ap.Master_Partner_ID__c = acc_partner_2.Id;
        update ap;
        
        Test.stopTest();
        
    }
}