unpackaged/main/default/objects/Account/fields/Blue_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Blue_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will hold the relevant county for account.</description>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <inlineHelpText>FL uses Small, Mid-Market and Large.
AR uses Small and Large.
HI uses the others.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contain Group Lookup</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner Accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>This field contains Contact type Pick list value</description>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Group Contact</fullName>
            </value>
            <value>
                <fullName>Medical Service Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Partner Rep</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Authorized Rep/POA</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Enrollment Contact</fullName>
            </value>
            <value>
                <fullName>Funeral Home</fullName>
            </value>
            <value>
                <fullName>Health Provider</fullName>
            </value>
            <value>
                <fullName>Other Business Entity Contact</fullName>
            </value>
            <value>
                <fullName>Other Service Provider</fullName>
            </value>
            <value>
                <fullName>Carrier Contact</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Student Child</fullName>
            </value>
            <value>
                <fullName>Domestic Partner</fullName>
            </value>
            <value>
                <fullName>Disabled Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This object will be used to save data of all counties.</description>
    <label>County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task/recordTypes/Claims.recordType-meta.xml
<RecordType>
    <fullName>Claims</fullName>
    <active>true</active>
    <label>Claims</label>
</RecordType>

unpackaged/main/default/globalValueSets/Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>Large</fullName>
    </customValue>
    <customValue>
        <fullName>CRG</fullName>
    </customValue>
    <customValue>
        <fullName>ACA</fullName>
    </customValue>
    <customValue>
        <fullName>MRG</fullName>
    </customValue>
    <customValue>
        <fullName>ASO/AFM</fullName>
    </customValue>
    <customValue>
        <fullName>RRG</fullName>
    </customValue>
    <customValue>
        <fullName>State</fullName>
    </customValue>
    <customValue>
        <fullName>FED</fullName>
    </customValue>
    <customValue>
        <fullName>Mid Market</fullName>
        <isActive>false</isActive>
        <label>Mid Market</label>
    </customValue>
    <customValue>
        <fullName>Large Market</fullName>
        <isActive>false</isActive>
        <label>Large Market</label>
    </customValue>
    <customValue>
        <fullName>Small Market</fullName>
        <isActive>false</isActive>
        <label>Small Market</label>
    </customValue>
    <description>Contains the picklist values for segment.</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TaskTrgTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TaskTrgTest {

    static testMethod void myUnitTest() {
    
        
        string BC_Code_1 = 'A008';
        string Segment_1 = 'Mid-Market';
        //county__c countyTest = USAbleUtility.CreateCounty();
        //insert countyTest;
        
         //insert partner account
        //Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        //insert acc_partner;
                
        Account acc= new Account();
        acc.Name='Account 1';
        //acc.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc.Type = 'Master Group';
        acc.Industry = 'Computer';
        acc.ShippingCountry = 'US';
        acc.BillingStreet = '16th';
        acc.BillingCity = 'Chicago';
        acc.BillingState = 'IL';
        acc.BillingCountry = 'US';
        acc.BillingPostalCode = '25250';        
        //acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        //acc.County__c = countyTest.Id;
        
        insert acc;
        
        
        Contact cont = new Contact();
        cont.FirstName = 'Contact';
        cont.LastName = '01';
        cont.AccountId = acc.Id; 
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        cont.Contact_Type__c = 'Group Contact';
        
        insert cont;
        
        User U = [select id from User WHERE Profile.Name Like '%Standard Claims User%' AND IsActive = true limit 1];
        Task t = new Task(Ownerid = U.id,Subject = 'Test',Whoid = cont.id,Whatid = Acc.id,Status = 'Pending',Priority = 'Low',Description = 'Test');
        insert t; //Note:While giving this insert check the required fields for task and include it above
        
        System.RunAs(u){
            Try{
                delete t;
                }
            catch (DmlException e) {
                System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' ,e.getDmlStatusCode(0) );
            }
        }
        
        // Zaid Code Ends Here
    }
}