unpackaged/main/default/objects/Account/fields/Blue_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Blue_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blue Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Blue Rep Name must be a contact with record type of Partner Rep whose account is the same as the Partner account</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Rep</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partner__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Group_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LSV_Business__c.field-meta.xml
<CustomField>
    <fullName>LSV_Business__c</fullName>
    <inlineHelpText>&#39;Medical Only&#39; - Master Group has only medical asset
&#39;Medical and Ancillary&#39; - Master Group has medical asset and at least one ancillary asset
&#39;Ancillary Only&#39; - Master Group has no medical asset and at least one ancillary asset</inlineHelpText>
    <label>LSV Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LSV Customer</fullName>
            </value>
            <value>
                <fullName>Medical Only</fullName>
            </value>
            <value>
                <fullName>Ancillary Only</fullName>
            </value>
            <value>
                <fullName>Medical and Ancillary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Manually_Create_Opp__c.field-meta.xml
<CustomField>
    <fullName>Manually_Create_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is being used in Opportunity creation batch.</description>
    <label>Manually Create Opp</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Manually_Create_Opp_User__c.field-meta.xml
<CustomField>
    <fullName>Manually_Create_Opp_User__c</fullName>
    <description>This field is being used in Auto create Opportunity batch.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Manually Create Opp User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Run_Opp_Batch__c.field-meta.xml
<CustomField>
    <fullName>Run_Opp_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in batch that automatically creates opportunities.</description>
    <label>Create Opportunity?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Batch_Created__c.field-meta.xml
<CustomField>
    <fullName>Batch_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It indicates, if an opportunity has been auto created by the batch job. Used in batch that automatically creates opportunities</description>
    <label>Auto Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Title</field>
            <operation>equals</operation>
            <value>BC Rep</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Opportunity Sales Process</businessProcess>
    <description>This handles both sales renewal process</description>
    <label>Sales</label>
</RecordType>

unpackaged/main/default/classes/OppBatchHelper.cls
public class OppBatchHelper {
    
    public list <Opportunity> CreateOpp(Set <Id> SetofAccId){
        system.debug('OppBatchHelper Class '+SetofAccId);
        List <Account> lstAccounts = new list <Account>([SELECT ID, Name, Group_Anniversary_Date__c, Blue_Rep_Name__c,  Manually_Create_Opp__c, Manually_Create_Opp_User__c, LSV_Business__c FROM Account Where Id IN : SetofAccID]);
        List <Opportunity> lstOppToAdd = new List <Opportunity>();
        //Id EDIId = [SELECT Id, LastName FROM User where LastName = 'EDI' and IsActive = true limit 1].id;
        Id EDIId = [SELECT Id, LastName FROM User where LastName = 'SFAdmin' and IsActive = true limit 1].id;        
        Integer month;
        Integer year;
        system.debug('OppBatchAccounts '+lstAccounts);
        List <AccountTeamMember> lstACTMem = new List <AccountTeamMember>();
        lstACTMem = [SELECT AccountId,Id,TeamMemberRole,Title FROM AccountTeamMember where TeamMemberRole = 'Sales Executive' AND isdeleted = false];
        Map <Id, Id> MapofAccIdAndAccTMemId = new Map <Id, Id>();
        for (AccountTeamMember ACTM : [SELECT AccountId,Id,UserId, TeamMemberRole,Title FROM AccountTeamMember where AccountId IN : lstAccounts])
        {
            if(ACTM.TeamMemberRole == 'Sales Executive')
            {
                MapofAccIdAndAccTMemId.put(ACTM.AccountId, ACTM.UserId);
            }
        }
        
        
        for (Account AC : lstAccounts)
        {
            Opportunity Op = new Opportunity();
            Op.Name = 'New Opp.';
            //Op.Type = 'Cross Sell';
            Op.Effective_Date__c = AC.Group_Anniversary_Date__c;
            Op.AccountId = AC.Id;
            Op.Partner_Rep__c = AC.Blue_Rep_Name__c;
            Op.StageName = 'New';
            if(AC.Manually_Create_Opp__c == true)
            {
                Op.Batch_Created__c = false;
            }
            else{
                Op.Batch_Created__c = true;
            }
            
            //Sukesh Nandella - To account for the new Opp TYpes 05/16/2023
            
            if(AC.LSV_Business__c == 'Medical Only')
            {
                Op.Type = 'Cross Sell';
            }
            else{
                Op.Type = 'Up Sell';
            }
            
            if(MapofAccIdAndAccTMemId != null)
            {
                if(MapofAccIdAndAccTMemId.get(Op.AccountId) != null)
                {
                    Op.OwnerId = MapofAccIdAndAccTMemId.get(Op.AccountId);
                }
                else {
                    Op.OwnerId = EDIId;
                }
            }
            if (AC.Manually_Create_Opp__c == true)
                Op.OwnerId = AC.Manually_Create_Opp_User__c;
            
            month = AC.Group_Anniversary_Date__c.month();
            year = AC.Group_Anniversary_Date__c.year();
            /*
            if(month == 1)
            {
                year= year - 1;
                date myDate = date.newInstance(year, 12, 15);
                Op.CloseDate = myDate;
            }
            else {
                date mDate = date.newInstance(year, month - 1, 15);
                Op.CloseDate = mDate;
            }
            */
            
            //date mDate = date.newInstance(year, month + 1, 15);
            date mDate = AC.Group_Anniversary_Date__c;
            Op.CloseDate = mDate+14;
            
            
            lstOppToAdd.add(Op);
        }
        
        system.debug('List of Opp Created '+lstOppToAdd);
        insert lstOppToAdd;
        
        list <Account> lstAccountsToReupdate = new List <Account>();
        for (Account A : lstAccounts)
        {
            A.Run_Opp_Batch__c = false;
            A.Manually_Create_Opp__c = false;
            lstAccountsToReupdate.add(A);
        }
        update lstAccountsToReupdate;
        
        
        
        return lstOppToAdd;
    }

}