unpackaged/main/default/objects/Account/fields/Blue_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Blue_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Blue Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will hold the relevant county for account.</description>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <inlineHelpText>FL uses Small, Mid-Market and Large.
AR uses Small and Large.
HI uses the others.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this field is populated on a Partner record, the Opportunities, Contacts, and Activities are moved over to the Master Group, chatter post created on master group, and Prospect record is deleted.</description>
    <inlineHelpText>Enter the name of the master group to merge this Prospect with the specified Master Group.</inlineHelpText>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Master_Group</value>
        </filterItems>
        <filterItems>
            <field>Account.Partner__c</field>
            <operation>equals</operation>
            <valueField>$Source.Partner__c</valueField>
        </filterItems>
        <infoMessage>You can only associate a Prospect with a Master Group</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Master Group)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contain Group Lookup</description>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Accounts</description>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner Accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <formula>TEXT(Contact.Contact_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a lookup of Account Object</description>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Master Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Group Cases</relationshipLabel>
    <relationshipName>Master_Group_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Contact lookup</description>
    <label>Member</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (1 AND 3 AND 4 AND 5) OR (1 AND 6)</booleanFilter>
        <errorMessage>The Case Contact is not currently associated to a System Group within Salesforce.</errorMessage>
        <filterItems>
            <field>Contact.Membership_Count__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>$Source.Reason</field>
            <operation>equals</operation>
            <value>Agent/Member</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Member</value>
        </filterItems>
        <filterItems>
            <field>$Source.Reason</field>
            <operation>equals</operation>
            <value>Group/Member</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Reason</field>
            <operation>notEqual</operation>
            <value>Group/Member, Agent/Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Member Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>This field contains Contact type Pick list value</description>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Group Contact</fullName>
            </value>
            <value>
                <fullName>Medical Service Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Partner Rep</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Authorized Rep/POA</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Enrollment Contact</fullName>
            </value>
            <value>
                <fullName>Funeral Home</fullName>
            </value>
            <value>
                <fullName>Health Provider</fullName>
            </value>
            <value>
                <fullName>Other Business Entity Contact</fullName>
            </value>
            <value>
                <fullName>Other Service Provider</fullName>
            </value>
            <value>
                <fullName>Carrier Contact</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Student Child</fullName>
            </value>
            <value>
                <fullName>Domestic Partner</fullName>
            </value>
            <value>
                <fullName>Disabled Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Group__c.Master_Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Agents working for agency</description>
    <label>Agent</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <description>Member Service Contacts</description>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This object will be used to save data of all counties.</description>
    <label>County</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>System Admin Groups Object</description>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Group__c/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <description>Junction Object To Link Members to Groups</description>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Member__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Membership</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>Large</fullName>
    </customValue>
    <customValue>
        <fullName>CRG</fullName>
    </customValue>
    <customValue>
        <fullName>ACA</fullName>
    </customValue>
    <customValue>
        <fullName>MRG</fullName>
    </customValue>
    <customValue>
        <fullName>ASO/AFM</fullName>
    </customValue>
    <customValue>
        <fullName>RRG</fullName>
    </customValue>
    <customValue>
        <fullName>State</fullName>
    </customValue>
    <customValue>
        <fullName>FED</fullName>
    </customValue>
    <customValue>
        <fullName>Mid Market</fullName>
        <isActive>false</isActive>
        <label>Mid Market</label>
    </customValue>
    <customValue>
        <fullName>Large Market</fullName>
        <isActive>false</isActive>
        <label>Large Market</label>
    </customValue>
    <customValue>
        <fullName>Small Market</fullName>
        <isActive>false</isActive>
        <label>Small Market</label>
    </customValue>
    <description>Contains the picklist values for segment.</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseReasonTrigTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CaseReasonTrigTest {
    
    static testMethod void myUnitTest1() {
        Test.startTest();
        
        // These Lines are added by Zaid to correct the test class
        
        Id RecordTypeIdPR = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Partner Rep').getRecordTypeId();
        Id RecordTypeIdAgent = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Id RecordTypeIdGroup = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        Id RecordTypeIdMember = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        string BC_Code_1 = 'A008';
        string Segment_1 = 'Mid-Market';
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        // Zaid Modification ends here
        
        Account acc= new Account();
        acc.Name='Account 1';
        //acc.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc.Type = 'Master Group';
        acc.Industry = 'Computer';
        acc.ShippingCountry = 'US';
        acc.BillingStreet = '16th';
        acc.BillingCity = 'Chicago';
        acc.BillingState = 'IL';
        acc.BillingCountry = 'US';
        acc.BillingPostalCode = '25250';
        
        // Zaid code here
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        // Zaid code ends here
        
        insert acc;
        
        Group__c group11 = new Group__c();
        group11.Name = 'Test group';
        group11.Master_Group__c = acc.Id;
        
        insert group11;
        
        Contact cont = new Contact();
        cont.FirstName = 'Contact';
        cont.LastName = '01';
        cont.AccountId = acc.Id; 
        cont.RecordTypeId = RecordTypeIdGroup ; // This line is added by Zaid
        cont.Contact_Type__c = 'Group Contact';
        
        insert cont;
        
        Member__c member = new Member__c();
        member.Member__c = cont.Id;
        member.Group__c = group11.Id;
        insert member;   
        // Rick added additional member 
        
        Contact cont2 = new Contact();
        cont2.FirstName = 'Membercontact';
        cont2.LastName = '01';
        cont2.AccountId = acc.Id; 
        cont2.RecordTypeId = RecordTypeIdMember ; // This line is added by Rick
        cont2.Contact_Type__c = 'Member';
        cont2.Group__c = group11.id;
        insert cont2;
        
        Member__c member2 = new Member__c();
        member2.Member__c = cont2.Id;
        member2.Group__c = group11.Id;
        insert member2;  
        // Zaid Added this
        
        Case case1 = new Case();
        case1.AccountId=acc.Id;
        case1.ContactId = cont.Id;
        //case1.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Case' AND r.Name = 'Policy Services'  LIMIT 1].Id;
        case1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Policy Services').getRecordTypeId();
        case1.Status='New';
        case1.Priority = 'Medium';
        case1.Type = 'New Business Setup';
        case1.Origin = 'newbusiness@usablelife.com';
        //case1.Reason = 'Group/Member'; commented by Zaid
        case1.Reason = 'Group';
        
        insert case1;
        
        Test.stopTest();    
    }
    
    static testMethod void myUnitTest2() {
        Test.startTest();
        
        // These Lines are added by Zaid to correct the test class
        
        Id RecordTypeIdPR = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Partner Rep').getRecordTypeId();
        Id RecordTypeIdAgent = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Id RecordTypeIdGroup = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        Id RecordTypeIdMember = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        string BC_Code_1 = 'A008';
        string Segment_1 = 'Mid-Market';
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        // Zaid Modification ends here
        
        List <Account> lstAcc = New List<Account>();
        Account acc= new Account();
        acc.Name='Account 1';
        //acc.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc.Type = 'Master Group';
        acc.Industry = 'Computer';
        acc.ShippingCountry = 'US';
        acc.BillingStreet = '16th';
        acc.BillingCity = 'Chicago';
        acc.BillingState = 'IL';
        acc.BillingCountry = 'US';
        acc.BillingPostalCode = '25250';
        
        // Zaid code here
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        // Zaid code ends here        
        lstAcc.add(acc);        
        
        Account acc1= new Account();
        acc1.Name='Account 2';
        //acc1.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc1.Type = 'Master Group';
        acc1.Industry = 'Computer';
        acc1.ShippingCountry = 'US';
        acc1.BillingStreet = '16th';
        acc1.BillingCity = 'Chicago';
        acc1.BillingState = 'IL';
        acc1.BillingCountry = 'US';
        acc1.BillingPostalCode = '25250';
        lstAcc.add(acc1);
        
        Account AccAgency = New Account();
        AccAgency = USAbleUtility.CreateAgencyAccount();
        AccAgency.BillingStreet = 'asd';
        AccAgency.BillingCity = 'asd';
        AccAgency.BillingState = 'asd';
        AccAgency.BillingCountry = 'asd';
        AccAgency.BillingPostalCode = '123';
        lstAcc.add(AccAgency);
        
        insert lstAcc;
        //insert acc;
        
        acc.Id = lstAcc[0].Id;
        acc1.Id = lstAcc[1].Id; 
        AccAgency.Id = lstAcc[2].Id;
        
        Group__c group11 = new Group__c();
        group11.Name = 'Test group';
        group11.Master_Group__c = acc.Id;
        
        insert group11;
        
        List<Contact> lstCont = new List<Contact>();
        Contact cont = new Contact();
        cont.FirstName = 'Contact';
        cont.LastName = '01';
        cont.AccountId = acc.Id; 
        cont.RecordTypeId = RecordTypeIdGroup ; // This line is added by Zaid
        cont.Contact_Type__c = 'Group Contact';
        lstCont.add(cont);
        
        
        Contact cont1 = new Contact();
        cont1.FirstName = 'Contact';
        cont1.LastName = '02';
        //cont1.AccountId = acc1.Id; 
        cont1.AccountId = AccAgency.Id;
        cont1.Contact_Type__c = 'Agent';
        cont1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        //cont1.Group__c = group2.Id;        
        //insert cont1;
        lstCont.add(cont1);
        
        insert lstCont;
        //insert cont;
        cont.Id = lstCont[0].Id;
        cont1.Id = lstCont[1].Id;       
        
        
        Member__c member = new Member__c();
        member.Member__c = cont.Id;
        member.Group__c = group11.Id;
        insert member;   
        
        // Zaid Added this
        
        Case case4 = new Case();
        case4.AccountId=acc1.Id;
        case4.ContactId = cont1.Id;
        //case4.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Case' AND r.Name = 'Policy Services'  LIMIT 1].Id;
        case4.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Policy Services').getRecordTypeId();
        case4.Status='New';
        case4.Priority = 'Medium';
        case4.Type = 'New Business Setup';
        case4.Origin = 'newbusiness@usablelife.com';
        //case4.Reason = 'Group';
        case4.Reason = 'Agency Relationship';
        
        insert case4;      
        
        Test.stopTest();    
    }
    
    /*static testMethod void myUnitTest2() {
        Test.startTest();
        
        // These Lines are added by Zaid to correct the test class
        
        Id RecordTypeIdPR = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Partner Rep').getRecordTypeId();
        Id RecordTypeIdAgent = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Id RecordTypeIdGroup = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeId();
        Id RecordTypeIdMember = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        
        //insert county
        county__c countyTest = USAbleUtility.CreateCounty();
        insert countyTest;
        
        string BC_Code_1 = 'A008';
        string Segment_1 = 'Mid-Market';
        
        //insert partner account
        Account acc_partner = USAbleUtility.CreatePartnerAccount(); //account returned from utility class
        insert acc_partner;
        
        List <Account> lstAcc = New List<Account>();
        Account acc1= new Account();
        acc1.Name='Account 2';
        //acc1.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc1.Type = 'Master Group';
        acc1.Industry = 'Computer';
        acc1.ShippingCountry = 'US';
        acc1.BillingStreet = '16th';
        acc1.BillingCity = 'Chicago';
        acc1.BillingState = 'IL';
        acc1.BillingCountry = 'US';
        acc1.BillingPostalCode = '25250';        
        
        lstAcc.add(acc1);
        
        Account AccAgency = New Account();
        AccAgency = USAbleUtility.CreateAgencyAccount();
        AccAgency.BillingStreet = 'asd';
        AccAgency.BillingCity = 'asd';
        AccAgency.BillingState = 'asd';
        AccAgency.BillingCountry = 'asd';
        AccAgency.BillingPostalCode = '123';
        lstAcc.add(AccAgency);
        
        Account acc= new Account();
        acc.Name='Account 1';
        //acc.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc.Type = 'Master Group';
        acc.Industry = 'Computer';
        acc.ShippingCountry = 'US';
        acc.BillingStreet = '16th';
        acc.BillingCity = 'Chicago';
        acc.BillingState = 'IL';
        acc.BillingCountry = 'US';
        acc.BillingPostalCode = '25250';
        
        // Zaid code here
        acc.Partner__c = acc_partner.Id;
        acc.Blue_Territory_Code__c = BC_Code_1 ;
        acc.Market_Segment__c = Segment_1;
        acc.County__c = countyTest.Id;
        // Zaid code ends here
        
        lstAcc.add(acc);
        
        insert lstAcc;
        acc1.Id = lstAcc[0].Id;
        AccAgency.Id = lstAcc[1].Id;
        acc.Id = lstAcc[2].Id;  
        
        Group__c group2 = new Group__c();
        group2.Name = 'Test group2';
        group2.Master_Group__c = acc1.Id;        
        insert group2;      
        
        List<Contact> lstCont = new List<Contact>();
        Contact cont1 = new Contact();
        cont1.FirstName = 'Contact';
        cont1.LastName = '02';
        //cont1.AccountId = acc1.Id; 
        cont1.AccountId = AccAgency.Id;
        cont1.Contact_Type__c = 'Agent';
        cont1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        //cont1.Group__c = group2.Id;        
        //insert cont1;
        lstCont.add(cont1);
        
        Contact cont11 = new Contact();
        cont11.FirstName = 'Contact';
        cont11.LastName = '001';
        cont11.AccountId = acc.Id; 
        cont11.Contact_Type__c = 'Member';
        cont11.RecordTypeId = RecordTypeIdGroup; // This line is added by Zaid
        
        //insert cont11;
        lstCont.add(cont11);        
        insert lstCont;
        
        cont1.Id = lstCont[0].Id;
        cont11.Id = lstCont[1].Id;
        
        
        Case case3 = new Case();
        case3.AccountId=acc1.Id;
        case3.ContactId = cont1.Id;
        //case3.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Case' AND r.Name = 'Policy Services'  LIMIT 1].Id;
        case3.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Policy Services').getRecordTypeId();
        case3.Status='New';
        case3.Priority = 'Medium';
        case3.Type = 'New Business Setup';
        case3.Origin = 'newbusiness@usablelife.com';
        case3.Reason = 'Agent/Member';
        case3.Member__c = cont11.Id; 
        
        insert case3;        
        
        Test.stopTest();    
    }*/
    
}