unpackaged/main/default/objects/Account/fields/Group_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Group_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Anniversary Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Primary_Agency__c.field-meta.xml
<CustomField>
    <fullName>Sales_Primary_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Master Group has Medical then it will be medical agency else it will be life/dental agency.</inlineHelpText>
    <label>Primary Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Sales Primary Agency)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Line_Item_Stage__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Stage__c</fullName>
    <label>Line Item Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pursue</fullName>
                <default>true</default>
                <label>Pursue</label>
            </value>
            <value>
                <fullName>Waiting for Info</fullName>
            </value>
            <value>
                <fullName>Submitted for Quote</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost - Quoted</fullName>
            </value>
            <value>
                <fullName>Closed Lost - Not Quoted</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Next_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Sales_Price_Custom__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price_Custom__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field holds the sales price value for closed lost total price calculation.</description>
    <label>Sales Price Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line_for_Opp__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_for_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used in the code that creates the opportunities via batch, and it indicates that the product is a &#39;generic&#39; product line that could be added to an opportunity.</description>
    <label>Product Line for Opp</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/OppRenewalLineItemCreationBatch.cls
global without sharing class OppRenewalLineItemCreationBatch implements Database.Batchable<sObject>{
    
    Final Set <Id> SetOppId;
    Final Map <Id, Set<Id>> MapAccIdProId;
    Final List <OpportunityLineItem> lstOLI = new List <OpportunityLineItem>();
    List <Product2> lstProduct = new list <Product2>();
    list <PricebookEntry> lstPBE = new list <PricebookEntry>();
    list <Account> lstAccount;
    Map <Id, Id> MapOfProductIdPBE;
    
    Global OppRenewalLineItemCreationBatch(Set <Id> OppIds, Map <Id, Set<Id>> MapAccIdProdId){        
        SetOppId = OppIds;
        MapAccIdProId = new Map<Id, Set<Id>>(MapAccIdProdId);        
    }
    
    global Database.QueryLocator start (Database.BatchableContext BC){
        String Query;
        Query = 'SELECT ID, Name, AccountId FROM Opportunity Where Id IN :SetOppId';
        
        return Database.getQueryLocator(Query);  
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> lstOppFinal){
        
        lstProduct = [Select Id, Name from Product2 WHERE Product_Line_for_Opp__c = true];
        lstPBE = [SELECT Id,Name,Product2Id,UnitPrice FROM Pricebookentry WHERE PriceBook2.IsStandard=true AND IsActive = true];
        lstAccount = [SELECT Id, Name, Sales_Primary_Agency__c, Group_Anniversary_Date__c From Account where id IN : MapAccIdProId.keySet()];
        
        MapOfProductIdPBE = new Map <Id, Id>();
        for (PricebookEntry PP : lstPBE)
        {
            MapOfProductIdPBE.put(PP.Product2Id, PP.id);
        }
        List <Opportunity> lst_Opp = new List <Opportunity>();
        Map <Id, Account> MapAcc = new Map <Id,Account>(lstAccount);
        
        for (Opportunity Opp : lstOppFinal){
            
            lst_Opp.add(Opp);   
        }
        
        for (Opportunity O : lst_Opp)
        {
            Set <Id> SetPIds = new Set <Id>();
            
            if (MapAccIdProId.containskey(O.AccountId) )
            {
                SetPIds = MapAccIdProId.get(O.AccountId);
                For (Product2 P : lstProduct)
                {
                    if(!SetPIds.contains(P.Id))
                    {
                        OpportunityLineItem OLI = new OpportunityLineItem();
                        OLI.Line_Item_Stage__c = 'Pursue';
                        OLI.Quantity = 1;
                        OLI.Sales_Price_Custom__c = 0;
                        OLI.Broker_Agency__c = MapAcc.get(O.AccountId).Sales_Primary_Agency__c;                        
                        OLI.Next_Renewal_Date__c = MapAcc.get(O.AccountId).Group_Anniversary_Date__c.addMonths(12);
                        if (MapOfProductIdPBE.containskey(P.Id))
                        {
                            OLI.PricebookEntryId = MapOfProductIdPBE.get(P.Id);
                            OLI.OpportunityId = O.Id;
                            lstOLI.add(OLI);
                        }
                        else
                            system.debug('No Value found in PBE '+P.Id);
                    }
                }
            }
        }
        if (lstOLI.size() > 0)
            insert lstOLI;
    }
    
    global void finish(Database.BatchableContext BC){      
                
    }
}