unpackaged/main/default/objects/Account/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this field is populated on a Partner record, the Opportunities, Contacts, and Activities are moved over to the Master Group, chatter post created on master group, and Prospect record is deleted.</description>
    <inlineHelpText>Enter the name of the master group to merge this Prospect with the specified Master Group.</inlineHelpText>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Master_Group</value>
        </filterItems>
        <filterItems>
            <field>Account.Partner__c</field>
            <operation>equals</operation>
            <valueField>$Source.Partner__c</valueField>
        </filterItems>
        <infoMessage>You can only associate a Prospect with a Master Group</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Master Group)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>System Admin Groups Object</description>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Group__c/fields/Master_Group__c.field-meta.xml
<CustomField>
    <fullName>Master_Group__c</fullName>
    <label>Master Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TestGroupBuilder.cls
@IsTest
public with sharing class TestGroupBuilder extends TestSObjectBuilder {
  // keeps count of Instances to allow differentiating objects built;
  // e.g. 'Test Account 1', 'Test Account 2'
  // specifically, increments when build() is called.
  static Integer iteration = 0;

  public TestGroupBuilder() {
    setSObjectAndDefaultRecordType('Group__c', null);

    this.values.put('builderId', iteration + 1);
    addDefaultFieldsToValuesMap();
  }

  private TestGroupBuilder(TestGroupBuilder oldBuilder) {
    this.values = oldBuilder.values;
    this.SOBJECT_TYPE = oldBuilder.SOBJECT_TYPE;
    this.DEFAULT_SOBJECT_RECORD_TYPE = oldBuilder.DEFAULT_SOBJECT_RECORD_TYPE;
  }

  protected override TestSObjectBuilder cloneBuilder() {
    TestGroupBuilder newBuilder = new TestGroupBuilder(this);

    Integer newBuilderId = (Integer) newBuilder.values.get('builderId');
    newBuilder.values.put('builderId', newBuilderId + 1);
    return newBuilder;
  }

  // default values that apply to all instances across all tests
  protected override void addDefaultFieldsToValuesMap() {
    this.withName('Test Group ' + values.get('builderId'))
      .withMasterGroupId(null);
  }

  // candidate for abstract class -- using Type.forName() ??
  protected override void iterate() {
    TestGroupBuilder.iteration += 1;
  }

  // setters
  public TestGroupBuilder withName(String groupName) {
    values.put('Name', groupName);
    return (TestGroupBuilder) cloneBuilder();
  }

  public TestGroupBuilder withMasterGroupId(String accountId) {
    if (accountId != null) {
      values.put('Master_Group__c', accountId);
    }
    TestGroupBuilder returnBuilder = (TestGroupBuilder) cloneBuilder();
    return returnBuilder;
  }
}