unpackaged/main/default/objects/Account/fields/Open_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account Has Open Enrollment</description>
    <inlineHelpText>Account Has Open Enrollment</inlineHelpText>
    <label>Open Enrollment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Accounts</description>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Asset/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <description>Values in these three picklists should generally align, except Asset has a value for &#39;Medical&#39; not present in the other picklists: 
• Asset.Carrier__c 
• OpportunityProduct.Current_Carrier__c
• OpportunityProduct.Competitor_Name__c</description>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Hartford</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Lincoln National</fullName>
            </value>
            <value>
                <fullName>LSV</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Mutual of Omaha</fullName>
            </value>
            <value>
                <fullName>Pacific Guardian Life</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Protective</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Reliance Standard</fullName>
            </value>
            <value>
                <fullName>Soltice</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Sun Life</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Unum</fullName>
            </value>
            <value>
                <fullName>USAble</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Initial_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Initial_Contracts__c</fullName>
    <inlineHelpText>Contracts at point of sale for a new benefit OR Contracts at point of renewal for an existing benefit. 
This will reset at the time of renewal.</inlineHelpText>
    <label>Initial Contracts</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Initial_Eligibles__c.field-meta.xml
<CustomField>
    <fullName>Initial_Eligibles__c</fullName>
    <inlineHelpText>Medical Eligibles at point of sale for a new benefit OR Medical Eligibles at point of renewal for an existing benefit.
This will reset at the time of renewal.</inlineHelpText>
    <label>Initial Eligibles</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Initial_Premium__c.field-meta.xml
<CustomField>
    <fullName>Initial_Premium__c</fullName>
    <inlineHelpText>Annualized Premium at point of sale for a new benefit OR Premium at point of renewal for an existing benefit.
This will reset at the time of renewal.</inlineHelpText>
    <label>Initial Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <formula>TEXT(Contact.Contact_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>This field contains the Case Sub Type</description>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1099 related questions or issues</fullName>
            </value>
            <value>
                <fullName>51+ sized groups</fullName>
            </value>
            <value>
                <fullName>Accelerated Living Benefit</fullName>
            </value>
            <value>
                <fullName>AccessAble</fullName>
            </value>
            <value>
                <fullName>Accumulator Reports</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Sent</fullName>
            </value>
            <value>
                <fullName>Add Add’l Users</fullName>
            </value>
            <value>
                <fullName>Add Open Enrollment Period</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Admin Access</fullName>
            </value>
            <value>
                <fullName>Administrative Rules</fullName>
            </value>
            <value>
                <fullName>After Upload Recon</fullName>
            </value>
            <value>
                <fullName>Age Unlock</fullName>
            </value>
            <value>
                <fullName>Amendments</fullName>
            </value>
            <value>
                <fullName>Anniversary Date Change</fullName>
            </value>
            <value>
                <fullName>Anniversary Error</fullName>
            </value>
            <value>
                <fullName>Annual Enrollment</fullName>
            </value>
            <value>
                <fullName>AOR Change</fullName>
            </value>
            <value>
                <fullName>Appeal</fullName>
            </value>
            <value>
                <fullName>Appeals Status</fullName>
            </value>
            <value>
                <fullName>Applications</fullName>
            </value>
            <value>
                <fullName>Application Status</fullName>
            </value>
            <value>
                <fullName>Appointment of Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Approved for Production</fullName>
            </value>
            <value>
                <fullName>Appt System Setup</fullName>
            </value>
            <value>
                <fullName>Appt Termination</fullName>
            </value>
            <value>
                <fullName>Appt Verification</fullName>
            </value>
            <value>
                <fullName>ASO Benefit Changes</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Open Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <description>This field contains Contact type Pick list value</description>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Group Contact</fullName>
            </value>
            <value>
                <fullName>Medical Service Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Partner Rep</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Authorized Rep/POA</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Enrollment Contact</fullName>
            </value>
            <value>
                <fullName>Funeral Home</fullName>
            </value>
            <value>
                <fullName>Health Provider</fullName>
            </value>
            <value>
                <fullName>Other Business Entity Contact</fullName>
            </value>
            <value>
                <fullName>Other Service Provider</fullName>
            </value>
            <value>
                <fullName>Carrier Contact</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Student Child</fullName>
            </value>
            <value>
                <fullName>Domestic Partner</fullName>
            </value>
            <value>
                <fullName>Disabled Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Open_Enrollment__c/Open_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Open Enrollment</label>
    <nameField>
        <displayFormat>OE-{00000}</displayFormat>
        <label>Open Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Open_Enrollment__c/fields/Accepted_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Enrollment__c</fullName>
    <label>Accepted Enrollment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NA_NO_Yes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Open_Enrollment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Open Enrollments</relationshipLabel>
    <relationshipName>Renewal_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASO / ATP STD</fullName>
            </value>
            <value>
                <fullName>Copay PPO</fullName>
            </value>
            <value>
                <fullName>Indiv. Dental</fullName>
            </value>
            <value>
                <fullName>Indiv. Life</fullName>
            </value>
            <value>
                <fullName>Indiv. Worksite</fullName>
            </value>
            <value>
                <fullName>Indemnity/PAR</fullName>
            </value>
            <value>
                <fullName>LTD / VLTD</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>PPO</fullName>
            </value>
            <value>
                <fullName>PPO+</fullName>
            </value>
            <value>
                <fullName>Prepaid/DHMO</fullName>
            </value>
            <value>
                <fullName>STD / VSTD</fullName>
            </value>
            <value>
                <fullName>TDI</fullName>
            </value>
            <value>
                <fullName>True Group Life</fullName>
            </value>
            <value>
                <fullName>VADD</fullName>
            </value>
            <value>
                <fullName>VGTL</fullName>
            </value>
            <value>
                <fullName>Worksite ECR</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Non-Integrated</fullName>
            </value>
            <value>
                <fullName>PFML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field specifies the type of product.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LSV</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Dental Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/NA_NO_Yes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
        <default>true</default>
        <label>N/A</label>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <masterLabel>NA_NO_Yes</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpenEnrollmentTRGTest.cls
@isTest
public class OpenEnrollmentTRGTest {
    final String WorksiteCI = 'Worksite CI';
    Static testMethod void myUnitTest1() {
 
    // Setup Test Data
     Profile p = [SELECT Id FROM Profile WHERE Name='USAble System Administrator'];
        User u = [SELECT Id FROM User WHERE profileId = :p.Id LIMIT 1];
        test.startTest();
        List <Account> lstAcc = New List<Account>();
        Account acc= new Account();
        // Get Group Contact ID       
        Id RecordTypeIdGroup = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Group Contact').getRecordTypeID();
     // Create Account of Master Group Record Type
         id MasterGroupRTID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeID();
          Account acc1= new Account();
        acc1.Name='Account 2';
        //acc1.RecordTypeId = [Select r.SobjectType, r.Id, r.Name  From RecordType r WHERE r.SobjectType = 'Account' AND r.Name = 'Master Group'  LIMIT 1].Id;
        acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        acc1.Type = 'Master Group';
        acc1.Industry = 'Computer';
        acc1.ShippingCountry = 'US';
        acc1.BillingStreet = '16th';
        acc1.BillingCity = 'Little Rock';
        acc1.BillingState = 'Ar';
        acc1.BillingCountry = 'US';
        acc1.BillingPostalCode = '72223';
        insert acc1;
        // Create and insert a Group Contact
        List<Contact> lstCont = new List<Contact>();
        Contact cont = new Contact();
        cont.FirstName = 'Contact';
        cont.LastName = '01';
        cont.AccountId = acc1.Id; 
        cont.RecordTypeId = RecordTypeIdGroup ; 
        cont.Contact_Type__c = 'Group Contact';
        lstCont.add(cont);
        insert lstCont;
        // Create and Insert customer Service Open Enrollment Case
        Case case4 = new Case();
        case4.AccountId=acc1.Id;
        case4.ContactId = cont.Id;
        case4.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Service').getRecordTypeId();
        case4.Status='New';
        case4.Priority = 'Medium';
        case4.Type = 'Enrollment';
        case4.Sub_Type__c = 'Open Enrollment';
        case4.Origin = 'Phone';
        //case4.Reason = 'Group';
        case4.Reason = 'Group';
         insert Case4;
        // Create and Insert Agency Account. 
        Account acc_agency = new Account();
        acc_agency = USAbleUtility.CreateAgencyAccount(); //account returned from utility class
        insert acc_agency;
        // Create and Insert Product
        Product2 prd = new Product2();
        prd.Name = 'VGTL';
        prd.Type__c = 'LSV';
        prd.ProductCode = 'VGTL';
        prd.Family = 'GRP LIFE';
        prd.Product_Category__c = 'True Group Life';
        prd.isActive  = true;
        insert PRD;
        //create asset and Insert Asset
        asset ast = new asset();
        ast.name = 'VGTL';
        ast.Product2Id = prd.Id;
        ast.AccountId = acc1.Id;
        ast.Renewal_date__c = date.today() + 50;
        ast.Carrier__c = 'BCBS';
        ast.Initial_Contracts__c  = 20;
        ast.Initial_Eligibles__c = 200;
        ast.Initial_Premium__c = 2000;	
        Insert ast;
        // create asset and Insert Asset Child
        asset chast = new asset();
        chast.name = 'VGTL Child';
        chast.Product2Id = prd.Id;
        chast.AccountId = acc1.Id;
        chast.Renewal_date__c = date.today() + 50;
        chast.Carrier__c = 'BCBS';
        chast.Initial_Contracts__c  = 5;
        chast.Initial_Eligibles__c = 00;
        chast.Initial_Premium__c = 400;  
        Insert chast;
       // create asset and Insert Asset Spouse
        asset sast = new asset();
        sast.name = 'VGTL Spouse';
        sast.Product2Id = prd.Id;
        sast.AccountId = acc1.Id;
        sast.Renewal_date__c = date.today() + 50;
        sast.Carrier__c = 'BCBS';
        sast.Initial_Contracts__c  = 5;
        sast.Initial_Eligibles__c = 00;
        sast.Initial_Premium__c = 800;  
        Insert sast;
         // create Open Enrollment and Insert Asset
        Open_Enrollment__c OE = new Open_Enrollment__c();
        OE.Accepted_Enrollment__c = 'Yes';
        OE.Case__c = Case4.Id;
        OE.Product_Type__c = 'VGTL';
       Insert OE;
    }
}