unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <description>Agency Accounts</description>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Agency_MasterGroups__c/Agency_MasterGroups__c.object-meta.xml
<CustomObject>
    <description>This object is used to create  a many to many relationship between Groups and Agencies.</description>
    <label>Agency/Master Group</label>
    <nameField>
        <displayFormat>AP-{000}</displayFormat>
        <label>Agency/Masters Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies/Master Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agency_MasterGroups__c/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account record type must be an Agency</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Groups</relationshipLabel>
    <relationshipName>Broker_Agency</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <description>Values in these three picklists should generally align, except Asset has a value for &#39;Medical&#39; not present in the other picklists: 
• Asset.Carrier__c 
• OpportunityProduct.Current_Carrier__c
• OpportunityProduct.Competitor_Name__c</description>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Hartford</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Lincoln National</fullName>
            </value>
            <value>
                <fullName>LSV</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Mutual of Omaha</fullName>
            </value>
            <value>
                <fullName>Pacific Guardian Life</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Protective</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Reliance Standard</fullName>
            </value>
            <value>
                <fullName>Soltice</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Sun Life</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Unum</fullName>
            </value>
            <value>
                <fullName>USAble</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/AssetTrgTest.cls
/*
Name        : AssetTrgTest
Author      : Munazza Ahmed
Date        : 8/5/2016
Purpose : Test class for coverage of trigger on Asset.
*/

@isTest
private class AssetTrgTest
{  
    public static testMethod void assetRelationshipTest()
    {
        //insert account
        Account acc_agency = new Account();
        acc_agency = USAbleUtility.CreateAgencyAccount(); //account returned from utility class
        insert acc_agency;
        
        //insert account
        Account acc_master = new Account();
        acc_master = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        insert acc_master;
        
        //insert agency master record
        Agency_MasterGroups__c agencyMaster = new Agency_MasterGroups__c();
        agencyMaster = USAbleUtility.CreateAgencyMasterGroup(acc_agency,acc_master);
        insert agencyMaster;
        
        //insert account
        Account acc_master_b = new Account();
        acc_master_b = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
        insert acc_master_b;
        
        //insert account
        Account acc_agency_b = new Account();
        acc_agency_b = USAbleUtility.CreateAgencyAccount(); //account returned from utility class
        insert acc_agency_b;
        
        //insert Product
        Product2 prd = new Product2();
        prd = USAbleUtility.CreateProuct(); //Product returned from utility class
        insert prd;
        
        //create asset
        asset ast = new asset();
        ast.name = 'Test Asset';
        ast.Product2Id = prd.Id;
        ast.AccountId = acc_master_b.Id;
        ast.Broker_Agency__c = acc_agency_b.Id;
        ast.Renewal_date__c = date.today();
        ast.Carrier__c = 'AIG';
        insert ast;
    }
}