unpackaged/main/default/objects/Case/fields/CvabClaim__c.field-meta.xml
<CustomField>
    <fullName>CvabClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Absence Claim</label>
    <referenceTo>cvab__Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>CvabClaim</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CveClaim__c.field-meta.xml
<CustomField>
    <fullName>CveClaim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Claim</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>CveClaim</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ClaimCreatedFromCase__e/ClaimCreatedFromCase__e.object-meta.xml
<CustomObject>
    <description>Transition Intake(case object) documents/files to cve and cvab Claims</description>
    <label>ClaimCreatedFromCase</label>
    <pluralLabel>ClaimCreatedFromCase</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ClaimCreatedFromCase__e/fields/CvabClaimId__c.field-meta.xml
<CustomField>
    <fullName>CvabClaimId__c</fullName>
    <description>Holds the Cvab Claim Id</description>
    <label>CvabClaimId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClaimCreatedFromCase__e/fields/CveClaimId__c.field-meta.xml
<CustomField>
    <fullName>CveClaimId__c</fullName>
    <description>Holds the Cve Claim Id</description>
    <label>CveClaimId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClaimCreatedFromCase__e/fields/IntakeCaseId__c.field-meta.xml
<CustomField>
    <fullName>IntakeCaseId__c</fullName>
    <description>Holds the Case Id</description>
    <label>IntakeCaseId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ContentDocumentLinkTriggerHelper.cls
public with sharing class ContentDocumentLinkTriggerHelper {
  private ContentDocumentLinkTriggerHandler.ContextVariables contxtVars;
  private static ContentDocumentLinkTriggerHelper instance = null;

  public static ContentDocumentLinkTriggerHelper getInstance() {
    if (instance == null) {
      instance = new ContentDocumentLinkTriggerHelper();
    }

    return instance;
  }

  public ContentDocumentLinkTriggerHelper withContextVars(
    ContentDocumentLinkTriggerHandler.ContextVariables contxtVars
  ) {
    this.contxtVars = contxtVars;
    return this;
  }

  public List<ClaimCreatedFromCase__e> getEventList() {
    Set<Id> caseIds = getCaseIds();
    List<Case> caseList = getCasesHavingClaims(caseIds);
    List<ClaimCreatedFromCase__e> eventList = getEvents(caseList);
    return eventList;
  }

  public List<ClaimCreatedFromCase__e> getEvents(List<Case> caseList) {
    List<ClaimCreatedFromCase__e> eventList = new List<ClaimCreatedFromCase__e>();
    for (Case cs : caseList) {
      ClaimCreatedFromCase__e clmCrtedFrmCs = new ClaimCreatedFromCase__e();
      clmCrtedFrmCs.CvabClaimId__c = cs.CvabClaim__c;
      clmCrtedFrmCs.CveClaimId__c = cs.CveClaim__c;
      clmCrtedFrmCs.IntakeCaseId__c = cs.Id;
      eventList.add(clmCrtedFrmCs);
    }
    return eventList;
  }

  public Set<Id> getCaseIds() {
    Set<Id> caseIds = new Set<Id>();
    for (ContentDocumentLink cdl : contxtVars.newList) {
      String sObjName = cdl.LinkedEntityId.getSObjectType()
        .getDescribe()
        .getName();
      if (sObjName == 'Case') {
        caseIds.add(cdl.LinkedEntityId);
      }
    }
    return caseIds;
  }

  public List<Case> getCasesHavingClaims(Set<Id> caseIds) {
    List<Case> caseList = [
      SELECT Id, CvabClaim__c, CveClaim__c
      FROM case
      WHERE Id IN :caseIds AND (CvabClaim__c != NULL OR CveClaim__c != NULL)
    ];
    return caseList;
  }
}