unpackaged/main/default/objects/Asset/fields/Active_Formula__c.field-meta.xml
<CustomField>
    <fullName>Active_Formula__c</fullName>
    <formula>If( OR( Renewal_Date__c &lt; TODAY(),  Cancellation_Date__c  &lt; Today()), false,true )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Competitor_Asset__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Asset__c</fullName>
    <formula>IF( 
   OR(ISPICKVAL(Carrier__c, &#39;BCBS&#39;) , ISPICKVAL(Carrier__c, &#39;USAble&#39;) , ISPICKVAL(Carrier__c, 
      &#39;LSV&#39;) , ISPICKVAL(Carrier__c, &#39;FCL&#39;)), 

false, 

true

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor Asset?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Current_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Current_Contracts__c</fullName>
    <label>Current Contracts</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Current_Eligibles__c.field-meta.xml
<CustomField>
    <fullName>Current_Eligibles__c</fullName>
    <inlineHelpText>Current Medical Eligibles</inlineHelpText>
    <label>Current Eligibles</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Current_Premium__c.field-meta.xml
<CustomField>
    <fullName>Current_Premium__c</fullName>
    <inlineHelpText>Current Annualized Premium</inlineHelpText>
    <label>Current Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Opp_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_Category__c</fullName>
    <formula>TEXT(Product2.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Product Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASO / ATP STD</fullName>
            </value>
            <value>
                <fullName>Copay PPO</fullName>
            </value>
            <value>
                <fullName>Indiv. Dental</fullName>
            </value>
            <value>
                <fullName>Indiv. Life</fullName>
            </value>
            <value>
                <fullName>Indiv. Worksite</fullName>
            </value>
            <value>
                <fullName>Indemnity/PAR</fullName>
            </value>
            <value>
                <fullName>LTD / VLTD</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>PPO</fullName>
            </value>
            <value>
                <fullName>PPO+</fullName>
            </value>
            <value>
                <fullName>Prepaid/DHMO</fullName>
            </value>
            <value>
                <fullName>STD / VSTD</fullName>
            </value>
            <value>
                <fullName>TDI</fullName>
            </value>
            <value>
                <fullName>True Group Life</fullName>
            </value>
            <value>
                <fullName>VADD</fullName>
            </value>
            <value>
                <fullName>VGTL</fullName>
            </value>
            <value>
                <fullName>Worksite ECR</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Non-Integrated</fullName>
            </value>
            <value>
                <fullName>PFML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DisplayAllAssetsOpportunities.cls
public class DisplayAllAssetsOpportunities {

    public Opportunity OpportunityInfo{get;set;}
    Public List<Asset> ast {get;set;}
    Public AggregateResult[] groupedResults {get;set;}
    
    public DisplayAllAssetsOpportunities (ApexPages.StandardController controller) {
        this.OpportunityInfo = (Opportunity)controller.getRecord();
        system.debug('Opp Info Here '+OpportunityInfo );
        Opportunity Opp = new Opportunity ();
        
        Opp = [Select Id, AccountId, Effective_Date__c  From Opportunity Where Id =: OpportunityInfo.Id ];
        Id AccId = [Select AccountId  From Opportunity Where Id =: OpportunityInfo.Id ].AccountId;
        system.debug('AccId '+AccId);
        Date d = Date.valueof(Opp.Effective_Date__c);
        //ast = [select ID, AccountId, name, Opp_Product_Category__c, Current_Premium__c, Current_Eligibles__c, Current_Contracts__c from Asset where Accountid=:AccId AND Active_Formula__c = true AND Renewal_Date__c <=: d  ORDER BY  Opp_Product_Category__c];
        
        //groupedResults = [Select   Opp_Product_Category__c, SUM(Current_Premium__c), SUM(Current_Eligibles__c), SUM(Current_Contracts__c), AccountId from Asset where Accountid=:AccId AND Active_Formula__c = true AND Renewal_Date__c <=: d  GROUP BY Opp_Product_Category__c, AccountId ];
        groupedResults = [select Account.Name a , Product2.Product_Category__c b, sum(Current_Premium__c) c , max(Current_Eligibles__c) d, max(Current_Contracts__c) e from Asset where Accountid=:AccId AND Active_Formula__c = true AND Effective_Date__c <=: d AND Competitor_Asset__c = false Group By Product2.Product_Category__c,Account.name];
        
        
        
        
        
//        OpportunityInfo=new Opportunity(id=OppId);
system.debug('zaid::ast ' + ast);
    }
    

}