unpackaged/main/default/objects/Asset/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Broker_Agent__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assets (Broker Agent)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <description>Values in these three picklists should generally align, except Asset has a value for &#39;Medical&#39; not present in the other picklists: 
• Asset.Carrier__c 
• OpportunityProduct.Current_Carrier__c
• OpportunityProduct.Competitor_Name__c</description>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>BCBS</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Hartford</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Lincoln National</fullName>
            </value>
            <value>
                <fullName>LSV</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Mutual of Omaha</fullName>
            </value>
            <value>
                <fullName>Pacific Guardian Life</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Protective</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Reliance Standard</fullName>
            </value>
            <value>
                <fullName>Soltice</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Sun Life</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Unum</fullName>
            </value>
            <value>
                <fullName>USAble</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Rate_Guarantee__c.field-meta.xml
<CustomField>
    <fullName>Rate_Guarantee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rate Guarantee</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_Director__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep Director)</relationshipLabel>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep Manager)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Partner_Rep_VP__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep VP</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Partner Rep VP)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <description>Member Service Contacts</description>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Title</field>
            <operation>equals</operation>
            <value>BC Rep</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Director__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep Director)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep Manager)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Territory_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Rep Territory Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Rep_VP__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Rep VP</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Rep VP)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Agent must align with Broker Agency</errorMessage>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <filterItems>
            <field>Contact.Agency_Branch__c</field>
            <operation>equals</operation>
            <valueField>$Source.Broker_Agency__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Broker_Agency__c.field-meta.xml
<CustomField>
    <fullName>Broker_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>Values in these three picklists should generally align, except Asset has a value for &#39;Medical&#39; not present in the other picklists: 
• Asset.Carrier__c 
• OpportunityProduct.Current_Carrier__c
• OpportunityProduct.Competitor_Name__c</description>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Assurant</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Hartford</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Lincoln National</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Mutual of Omaha</fullName>
            </value>
            <value>
                <fullName>Pacific Guardian Life</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Protective</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Reliance Standard</fullName>
            </value>
            <value>
                <fullName>Soltice</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Sun Life</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
            <value>
                <fullName>Unum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Line_Item_Stage__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Stage__c</fullName>
    <label>Line Item Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pursue</fullName>
                <default>true</default>
                <label>Pursue</label>
            </value>
            <value>
                <fullName>Waiting for Info</fullName>
            </value>
            <value>
                <fullName>Submitted for Quote</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost - Quoted</fullName>
            </value>
            <value>
                <fullName>Closed Lost - Not Quoted</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
                <isActive>false</isActive>
                <label>Closed Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Next_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Rate_Guarantee__c.field-meta.xml
<CustomField>
    <fullName>Rate_Guarantee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rate Guarantee</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/OpportunityTrgUtil.cls
/*
Name        : OpportunityTrgUtil
Author      : Munazza Ahmed
Date        : 7/21/2016
Purpose : Utility class for Opportunity Trigger.
          - Return asset record list that is to be created.
modified by : Zaid
purpose : to add update partner rep fields on opportunity functionality added a new function
*/
public with sharing class OpportunityTrgUtil
{
    //variable to ensure single trigger of after update on workflow update
    public static  boolean firstRun = true;
    public static void InsertAssetForClosedOpp(set<Id> l_setOfOppIds, map<id,opportunity> l_mapOfOppIdAndOpp)
    {
        //initializing variables to be used in trigger
        set<id> setOfPrdId = new set<id>();
        
        list<Asset> listOfAsset = new list<Asset>();
        list<OpportunityLineItem> listOfOLI = new list<OpportunityLineItem>();
        list<OpportunityLineItem> listOfConvertedOli = new list<OpportunityLineItem>();
        
        map<id,Product2> mapOfOliIdandPrd = new map<id,Product2>();
        map<id,OpportunityLineItem> mapOfprdIdandOLI = new map<id,OpportunityLineItem>();
        //system.debug('Opp Util '+l_setOfOppIds.size());
        
        if (l_setOfOppIds.size() > 0)
        {
            for(OpportunityLineItem oli: [SELECT id, Line_Item_Stage__c, Product2Id, Renewal_Date__c, Competitor_Name__c,
                                          Next_Renewal_Date__c, opportunityId, Rate_Guarantee__c, Broker_Agency__c, Agent__c
                                          FROM OpportunityLineItem
                                          WHERE opportunityid in: l_setOfOppIds
                                          AND Product2Id <> null
                                          AND Competitor_Name__c <> null
                                          AND Next_Renewal_Date__c <> null
                                          AND (Line_Item_Stage__c = 'Closed Lost - Quoted' OR Line_Item_Stage__c = 'Closed Lost - Not Quoted')
                                          ]) 
            {
                listOfOLI.add(oli);    //store opportunity line item meeting appropriate conditions
                setOfPrdId.add(oli.Product2Id);    //store product id for relevant line item
                mapOfprdIdandOLI.put(oli.product2id,oli);    //store product id against line item
                system.debug('oli -> '+oli);
            }
            // Line_Item_Stage__c IN ('Closed Lost - Quoted', 'Closed Lost - Not Quoted')
            //get products in map for later assignment of product name to newly created asset name
            for(Product2 prd : [SELECT id, name
                                FROM Product2
                                WHERE Id in: setOfPrdId])
            {
                mapOfOliIdandPrd.put(mapOfprdIdandOLI.get(prd.id).id,prd);
            }
            
            system.debug('listOfOLI.size() '+listOfOLI.size()+'mapOfOliIdandPrd.size() '+mapOfOliIdandPrd.size()+'l_mapOfOppIdAndOpp.size() '+l_mapOfOppIdAndOpp.size());
            //get the list of assets to be inserted from utility class method
            if(listOfOLI.size()>0 && mapOfOliIdandPrd.size()>0 && l_mapOfOppIdAndOpp.size()>0)
            {
                for(OpportunityLineItem oli : listOfOLI)
                {
                    //create asset and populate relevant fields
                    asset ast = new asset();
                    ast.Name = mapOfOliIdandPrd.get(oli.id).Name;
                    ast.AccountId = l_mapOfOppIdAndOpp.get(oli.OpportunityId).AccountId;
                    ast.Product2Id = oli.Product2Id;
                    ast.Carrier__c = oli.Competitor_Name__c;
                    ast.Renewal_Date__c = oli.Next_Renewal_Date__c;
                    ast.Rate_Guarantee__c = oli.Rate_Guarantee__c;
                    ast.Broker_Agency__c = oli.Broker_Agency__c;
                    ast.Broker_Agent__c = oli.Agent__c;
                    listOfAsset.add(ast);
                }
                
            }
            if(listOfAsset.size() > 0)
            {
                insert listOfAsset;    //insert asset
                
            }
        } 
    }
    
    //Modification starts
    public static void UpdateOpportunityReps (List <Opportunity> lstOppToChange){
        
        Map <Id,Id> MapofOppAndAccount = new Map <Id,Id>();
        Map <Id,Account> MapofIdAndAccount = new Map <Id,Account>();
        Map <Id,Contact> MapofIdAndContact = new Map <Id,Contact>();
        Set <Id> setofOppOwnerId = new Set <Id>();
        Set <Id> setofAccountId = new Set <Id>();
        Set <Id> setofOppId = new Set <Id>();
        Set <Id> setofContactIds = new Set <Id>();
        List <Account> lstAccount = new list <Account>();
        List <Opportunity> lstOpportunity = new list <Opportunity>();
        Set <Id> SetOfOPPPId = new Set <Id>();
        for (Opportunity OPPP : lstOppToChange)
        {
            SetOfOPPPId.add(OPPP.Id);
        }
        List <Opportunity> lstOpp = new List <Opportunity>([Select OwnerId, id, name, StageName, AccountId , Partner_Rep__c, Partner_Rep_Territory_Code__c, Partner_Rep_Manager__c, Partner_Rep_Director__c, Partner_Rep_VP__c, isclosed from Opportunity where ID IN : SetOfOPPPId]);
        
        // iterate on list of opportunities
        for(Opportunity OP : lstOpp)
        {
            
            //if(OP.StageName == 'In Process' || OP.StageName == 'New')
            if(OP.IsClosed == false){
                setofAccountId.add(OP.AccountId);
                setofOppId.add(OP.Id);
                setofOppOwnerId.add(OP.OwnerId);
            }
        }

        // get list of accounts from opp list
		if (setofAccountId != null && setofAccountId.size() > 0)
        {
        	lstAccount = [select id, name, RecordTypeId,Blue_Rep_Name__c from Account where Id IN : setofAccountId];            
        }

        
        // storing accound id and account in a map
        if (lstAccount != null && lstAccount.size() > 0)
        {
            for (Account Acc : lstAccount)
            {
                MapofIdAndAccount.put(Acc.Id, Acc);
            }
            
        }
        //system.debug('Accounts ' +MapofIdAndAccount);
        Id RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Master Group').getRecordTypeId();
        Id ProspectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        //system.debug('RecordTypeId ' +RecordTypeId);
        
        // iterate over list of oppty to get account blue rep name
        for(Opportunity OPP : lstOpp)
        {
            system.debug('TempAccount '+MapofIdAndAccount.get(OPP.AccountId));
            Account TempAccount = MapofIdAndAccount.get(OPP.AccountId);
            //If((OPP.StageName == 'In Process' || OPP.StageName == 'New'  ) && (TempAccount.RecordTypeId == RecordTypeId || TempAccount.RecordTypeId == ProspectRecordTypeId ))
            If((OPP.IsClosed == False  ) && (TempAccount.RecordTypeId == RecordTypeId || TempAccount.RecordTypeId == ProspectRecordTypeId ))
            {
                //MapOfAccountAndContact.put(TempAccount,TempAccount.Blue_Rep_Name__c);
                setofContactIds.add(TempAccount.Blue_Rep_Name__c);
            }
        }
        
        List <Contact> lstContact = new List <Contact>();
        if (setofContactIds != null && setofContactIds.size() > 0)
        {
        	lstContact = [select id, name, Partner_Rep_Territory_Code__c, Partner_Rep_Manager__c, Partner_Rep_Director__c, Partner_Rep_VP__c from Contact where Id IN : setofContactIds ];    
        }
        
        //system.debug('lstContact ' +lstContact);
        
        if (lstContact != null && lstContact.size() > 0)
        {
        	for (Contact Con : lstContact)
            {
                MapofIdAndContact.put(Con.Id, Con);
            }
            
        }
        
        if (setofOppId != null && setofOppId.size() > 0)
        {
        	for (Opportunity OPPO : [Select id, name, StageName, AccountId , Partner_Rep__c, Partner_Rep_Territory_Code__c, Partner_Rep_Manager__c, Partner_Rep_Director__c, Partner_Rep_VP__c, isclosed from Opportunity where ID IN : setofOppId])
            {
                if(MapofIdAndAccount.get(OPPO.AccountId) != null)
                {
                Account TAccount = MapofIdAndAccount.get(OPPO.AccountId);
                
                if( MapofIdAndContact.get(TAccount.Blue_Rep_Name__c) != null )
                {
                    Contact Cont = MapofIdAndContact.get(TAccount.Blue_Rep_Name__c);
                    system.debug('Contact Id Here '+MapofIdAndContact.get(TAccount.Blue_Rep_Name__c));
                    //If((OPPO.StageName == 'In Process' || OPPO.StageName == 'New' ) && (TAccount.RecordTypeId == RecordTypeId || TAccount.RecordTypeId == ProspectRecordTypeId))
                    If((OPPO.IsClosed == False ) && (TAccount.RecordTypeId == RecordTypeId || TAccount.RecordTypeId == ProspectRecordTypeId))
                    {
                        /* if(OPPO.Partner_Rep__c != TAccount.Blue_Rep_Name__c 
                        && OPPO.Partner_Rep_Territory_Code__c != Cont.Partner_Rep_Territory_Code__c 
                        && OPPO.Partner_Rep_Manager__c != Cont.Partner_Rep_Manager__c 
                        && OPPO.Partner_Rep_Director__c != Cont.Partner_Rep_Director__c
                        && OPPO.Partner_Rep_VP__c != Cont.Partner_Rep_VP__c) */
                        //{
                            OPPO.Partner_Rep__c = TAccount.Blue_Rep_Name__c;
                            OPPO.Partner_Rep_Territory_Code__c = Cont.Partner_Rep_Territory_Code__c ;
                            OPPO.Partner_Rep_Manager__c = Cont.Partner_Rep_Manager__c;
                            OPPO.Partner_Rep_Director__c = Cont.Partner_Rep_Director__c;
                            OPPO.Partner_Rep_VP__c = Cont.Partner_Rep_VP__c;
                            lstOpportunity.add(OPPO);
                        //}
                    }
                 }
                }
            }
            
        }
        
        try
        {
            if (lstOpportunity.size() > 0)
            {
                Update lstOpportunity;
            }
        }
        catch (Exception ex)
        {
            if (ex.getMessage().contains('INSUFFICIENT_ACCESS_OR_READONLY'))
            {
                throw new OpportunityException(' You have insufficient privileges to update the open opportunity associated to this account. ');
            }
            else
            {
                throw new OpportunityException(' Error occured. Kindly check this error or contact your Salesforce Administrator ' + ex.getMessage());
            }           
        }
        
        
    
		
    }
    

	public static void ResetOpportunityTeam (List <Opportunity> lstOppToChange)
	{
        system.debug('ah::lstOppToChange ' + lstOppToChange);
        
        Set <Id> SetOfOPPPId = new Set <Id>();
        Set <Id> setofOppOwnerId = new Set <Id>();
        
        for (Opportunity Oppt : lstOppToChange)
        {
            SetOfOPPPId.add(Oppt.Id);
        }        
        
        List <Opportunity> lstOpp = new List <Opportunity>([Select OwnerId, id, name, StageName, AccountId, isclosed from Opportunity where ID IN : SetOfOPPPId]);
        
       if (lstOpp != null && lstOpp.size() > 0)
       {
        	for (Opportunity OPPP : lstOpp)
            {
                if(OPPP.IsClosed == false)
                {
                    setofOppOwnerId.add(OPPP.OwnerId);
                }
            }
       }
        
        // opp team is missing logic 
        Map<Id, List<UserTeamMember>> mapDefaultOppTeamDetail = new Map<Id, List<UserTeamMember>>();
        List<UserTeamMember> lstTeamMembers = null;
        
        //creating map of owner from userteamember.This will be used for team member role during opp. team addition in team.
        for (UserTeamMember utm : [select OpportunityAccessLevel, UserId, TeamMemberRole, OwnerId from UserTeamMember where OwnerId=:setofOppOwnerId])
        {
            if (!mapDefaultOppTeamDetail.containsKey(utm.OwnerId)){
                lstTeamMembers = new List<UserTeamMember>();
                lstTeamMembers.add(utm);
            } else {
                lstTeamMembers = mapDefaultOppTeamDetail.get(utm.OwnerId);
                lstTeamMembers.add(utm);
            }
            
            mapDefaultOppTeamDetail.put(utm.OwnerId, lstTeamMembers);               
        }        

        //creating map of opportunity team members
        Map<String, String> mapOTM = new Map<String, String>();
        
        for (OpportunityTeamMember otm : [select Id, TeamMemberRole, UserId, OpportunityId from OpportunityTeamMember where OpportunityId in :SetOfOPPPId])
        {
            String strKey = otm.OpportunityId + '-' + otm.UserId;
            if (!mapOTM.containsKey(strKey))
            {
                mapOTM.put(strKey, otm.TeamMemberRole);                    
            }
        }
        
        //managing list of opp. team member not in the above map
        List<OpportunityTeamMember> lstOTM = new List<OpportunityTeamMember>();
        for (Opportunity opt : [select Id, ownerId from opportunity where Id IN: SetOfOPPPId])
        {
            if (mapDefaultOppTeamDetail.containsKey(opt.ownerId)) {
                for (UserTeamMember usrTeamMember : mapDefaultOppTeamDetail.get(opt.ownerId)){
                    if (!mapOTM.containsKey(opt.Id+'-'+usrTeamMember.UserId)){
                        OpportunityTeamMember otm = new OpportunityTeamMember(OpportunityId = opt.Id, UserId = usrTeamMember.UserId, TeamMemberRole = usrTeamMember.TeamMemberRole, OpportunityAccessLevel=usrTeamMember.OpportunityAccessLevel);
                        lstOTM.add(otm);
                    }
                }
            }
        }
        
        if (lstOTM.size() > 0)
        {
            insert lstOTM;
        }
	}
    
    public class OpportunityException extends Exception {}
}