unpackaged/main/default/objects/UpdateCoverageClaimed__e/UpdateCoverageClaimed__e.object-meta.xml
<CustomObject>
    <label>UpdateCoverageClaimed</label>
    <pluralLabel>UpdateCoveragesClaimed</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/UpdateCoverageClaimed__e/fields/CoverageClaimedId__c.field-meta.xml
<CustomField>
    <fullName>CoverageClaimedId__c</fullName>
    <label>CoverageClaimedId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CoverageClaimedTriggerHelper.cls
public with sharing class CoverageClaimedTriggerHelper {
  private static CoverageClaimedTriggerHelper instance;
  private CoverageClaimedTriggerHandler.ContextVariable cv;

  public static CoverageClaimedTriggerHelper getInstance() {
    if (instance == null) {
      instance = new CoverageClaimedTriggerHelper();
    }
    return instance;
  }

  public void setContextVariable(
    CoverageClaimedTriggerHandler.ContextVariable cv
  ) {
    this.cv = cv;
  }

  public List<UpdateCoverageClaimed__e> createEvents() {
    List<UpdateCoverageClaimed__e> result = new List<UpdateCoverageClaimed__e>();
    for (cve__CoverageClaimed__c cc : cv.newList) {
      result.add(new UpdateCoverageClaimed__e(CoverageClaimedId__c = cc.id));
    }
    return result;
  }
}